timescale/promscale

.github/workflows/go.yml, .github/workflows/reviewdog.yml
This adds github actions to:
1) Build the go project
2) Run PRs through golangci and get feedback through reviewdog.
=> Add github actions

README.md, helm-chart/Chart.yaml
Adjusted version to 0.1.0-alpha.1 to reflect pre-release status.
=> Adjust helm chart version

LICENSE
The legal info from the appendix is already in NOTICE.
=> Remove Appendix from License

.github/workflows/go-report-card.yml, README.md, pkg/pgmodel/migrate_test.go, pkg/pgmodel/nan_test.go, pkg/pgmodel/pgx.go, pkg/pgmodel/query_integration_test.go, pkg/util/lock.go
There were several functions with cyclomatic complexities > 15 but other than one, all of them were in the tests, so I skipped fixing those.
=> Add go report card and fix some suggestions from it

pkg/pgmodel/query_integration_test.go
Switch to using a tmp dir Docker can bind to.
=> Fix docker test on OSX

cmd/timescale-prometheus/main.go
In HA mode, this metric will expose which of the connector had the
leader status and write privileges at specific times.
I've added the setting of the metric in `migrate` and `write` functions to be more explicit about setting it. 
Closes #36
=> Add leader status Prometheus metric

cmd/timescale-prometheus/main.go, cmd/timescale-prometheus/main_test.go
These tests cover most of the basic declaritive logic of the main package.
Some of the functions require a DB to be fully tested, to test them would
require major refactorings of the project so they are out-of-scope for this
commit.
=> Add main package unit tests

cmd/timescale-prometheus/main.go, cmd/timescale-prometheus/main_test.go
Connector should abort starting up if it cannot setup the required schema.
Closes #51
=> Fail connector startup on migration failure

pkg/internal/testhelpers/containers.go, pkg/internal/testhelpers/containers_test.go, pkg/log/log.go, pkg/pgmodel/migrate_test.go, pkg/pgmodel/testdata/expected/views.out, pkg/pgmodel/testdata/sql/views.sql, pkg/util/election_test.go
This adds the infrastructure for simple golden file tests.
Also add a simple golden file test for views.
=> Add infrastructure for psql-based golden tests

helm-chart/README.md, helm-chart/templates/svc-connector.yaml
=> Change service name in helm and describe expected secret

README.md
Not sure why this instruction was missing?
=> Add --devel flag to readme instruction

.github/workflows/go.yml, extension/DockerMakefile, extension/Dockerfile, extension/Makefile, extension/dependencies.makefile
This commits edits our CI to always create its own docker images, this should
catch any bugs edits to the extension could introduce.
=> Create Docker images in CI

pkg/pgmodel/pgx.go
Adds more logging when decompression happens.
=> Add info to logging during decompression

pkg/pgmodel/end_to_end_tests/create_test.go, pkg/pgmodel/pgx.go
The table name was not properly sanitized before.
=> Fix sanitizing the table name during ON CONFLICT DO NOTHING

cmd/timescale-prometheus/main.go, pkg/pgmodel/metrics.go, pkg/pgmodel/pgx.go, pkg/util/util.go
Adds metrics for duplicate and decompression calls.
=> Add metrics for inserters

extension/src/lib.rs, pkg/api/query.go, pkg/api/query_range.go, pkg/pgmodel/end_to_end_tests/main_test.go, pkg/pgmodel/end_to_end_tests/promql_endpoint_integration_test.go, pkg/pgmodel/pgx_test.go, pkg/pgmodel/query_builder.go, pkg/pgmodel/series_set.go, pkg/pgmodel/series_set_test.go, pkg/promql/engine.go
- Pass down the error handling better and log it.
- Also make use-docker flag only apply to the database.
- Improve promql tests to catch more cases. Some of the
cases don't pass. To be fixed in a followup commit.
=> Fix PromQL Differences for delta

pkg/pgmodel/pgx.go, pkg/pgmodel/pgx_test.go
Multi-valued inserts are significantly more performant than batched
single valued inserts, it also simplifies the code for finding how
many duplicates there were etc.
=> Use multi-valued inserts rather than batches

pkg/pgmodel/end_to_end_tests/migrate_test.go, pkg/pgmodel/migrate.go
=> Fix extension installed check for already migrated DB schema

pkg/pgmodel/sql_reader.go
Make sure errors are propagated or handled in all cases. Notably `appendTsRows()` now bubbles up any error it may encounter.
=> Fixup error handling of sql_reader

pkg/pgclient/client.go, pkg/pgmodel/sql_ingest.go
This commit contains two changes:
1. At startup, we now probe the database to determine the number of
connections it can handle in order to ensure we don't go over
that limit
2. We add a command line flag to override this setting for instances
where our heuristic is incorrect.
This should make the connector a better-behaved client of the database,
making it much less likely to starve out other clients, or itself.
fixes #187
=> Probe database for connection limit, and make it configurable

pkg/pgclient/client.go
=> Cap max number of connections used by default

pkg/internal/testhelpers/containers.go, pkg/pgmodel/upgrade_tests/upgrade_test.go
Test that upgrading from the previous version results in the same
database.
=> Add upgrade tests

pkg/internal/testhelpers/containers.go, pkg/internal/testhelpers/containers_test.go, pkg/pgmodel/end_to_end_tests/promql_endpoint_integration_test.go, pkg/pgmodel/upgrade_tests/upgrade_test.go
=> Test idempotent scripts as well

pkg/pgmodel/upgrade_tests/upgrade_test.go
`.dev` versions don't have an associated docker image, so we can't pull their docker image to test against. Instead skip back to the last version with an image to test against. Inductively, this will still test the entire chain of upgrades from the previous version.
=> Skip back to the previous released version when choosing a docker

.github/workflows/go.yml, pkg/api/labels_test.go, pkg/api/write_test.go, pkg/log/log.go, pkg/pgmodel/end_to_end_tests/main_test.go, pkg/pgmodel/ingestor.go, pkg/pgmodel/series_set_test.go, pkg/pgmodel/sql_ingest.go, pkg/pgmodel/sql_reader.go
This PR addresses some issues related to `golangci-lint` along with adding lint checks in CI since they were not being captured by our bot. Probably, since most bots tend to comment on the new changes, that might be a reason why these errors were not caught yet.
=> Fix golangci-lint issues and integrate the same on CI

pkg/pgmodel/end_to_end_tests/promql_endpoint_integration_test.go, pkg/pgmodel/end_to_end_tests/promql_label_endpoint_test.go, pkg/pgmodel/end_to_end_tests/promql_query_endpoint_test.go, pkg/pgmodel/end_to_end_tests/promql_series_endpoint_test.go
This commit adds additional tests which check that HTTP responses from
Prometheus and the connector contain matching HTTP headers.
=> Add HTTP header checking to end-to-end integration tests

cmd/timescale-prometheus/main.go, pkg/pgmodel/extension.go, pkg/pgmodel/migrate.go, pkg/util/util.go, pkg/version/version.go
Fixes: #235 
This PR adds support to check Timescaledb extension version at the start in order to warn the user in terms of incompatibility.
=> Adds support for checking Timescaledb version

pkg/prompb/README.md, pkg/prompb/custom.go, pkg/prompb/custom.ts.go, pkg/prompb/remote.pb.go, pkg/prompb/rpc.pb.gw.go, pkg/prompb/types.pb.go
=> Update promb from upstream commit 7de6046

extension/Readme.md
Add text about dependencies on Rust and PostgreSQL headers.
Fixes #247
=> Update extension compilation instructions

.github/workflows/go-scheduled.yml
Changing the extension Docker build to be run from external repository.
=> Fix scheduled GH action

README.md
=> Fix releases link

pkg/pgmodel/sql_test.go
`sql_tests.go` has two mock database connections: over time the old `mockPGXConn` has grown ad hoc logic for the various cases under test, but no real unifying principle, which made it difficult to determine what the exact behavior of the test should be and how to change tests, when the code under test changed. The newer `sqlRecorder` is much simpler, containing the query string, input, and output for each query we make to the database, and validating we make the queries we expected as we go; this makes it very simple to determine what broke when things change.
We always intended to refactor the remaining tests to use `sqlRecorder`, but it wasn't a high enough priority to finish. Well, now PR #304 is blocked on editing `sql_tests.go` to match the new logic, and it's simpler to do this …
=> REFACTOR sql_tests.go to use the new mock for sql_ingest tests

pkg/pgmodel/labels.go, pkg/pgmodel/querier.go, pkg/pgmodel/sql_reader.go
This commit also contains some light refactoring to make the code easier to
read and understand.
=> Add code documentation for query/read path of the connector

pkg/util/util.go, pkg/util/util_test.go
=> Mask password while printing config

pkg/pgmodel/sql_test.go
This PR finally finishes excising the old mock, and updates `mockBatch` to better fit `sqlReader`
=> Remove old mock

pkg/pgmodel/extension.go
=> Auto upgrade fixes

docs/cli.md, pkg/log/log.go, pkg/pgclient/client.go, pkg/pgmodel/sql_ingest.go, pkg/runner/runner.go
=> Add command line docs

README.md, docs/binary.md, docs/docker.md, docs/sql_schema.md, helm-chart/README.md, helm-chart/values.yaml
- Integrate the new docs content with links from appropriate places
- Add a documentation index/TOC
- Add a feature section and integrate the video
=> Docs update

README.md
=> Update Promscale scorecard for compliance test score

README.md, cmd/prom-migrator/README.md, cmd/prom-migrator/main.go
=> Adds user docs for prom-migrator

README.md, cmd/prom-migrator/README.md, cmd/prom-migrator/main.go
The input flags that contains planner config information was left to be implemented in the main file. This commit fixes it.
=> Fix: apply conf flag values to planner.

pkg/api/write.go, pkg/ha/ha_lock_client.go, pkg/ha/ha_parser.go, pkg/ha/ha_parser_test.go, pkg/ha/ha_service.go, pkg/ha/mock_ha_lock_client.go, pkg/ha/mock_ha_service.go, pkg/ha/state.go, pkg/pgclient/config.go, pkg/pgmodel/ingestor/ingestor.go, pkg/pgmodel/ingestor/ingestor_interface.go, pkg/pgmodel/ingestor/ingestor_test.go, pkg/pgmodel/ingestor/inserter.go, pkg/pgmodel/model/labels.go, pkg/runner/runner.go
HA Improvements:
1. Added tests for HA parser. 
2. Extended ingestion checks to verify not only `minT` is after `leaseStart` but also `maxT` is before `leaseUntil`. 
3. Modified a few conditions based on local testing.
Signed-off-by: Vineeth Pothulapati <vineethpothulapati@outlook.com>
=> ha improvements

docs/docker.md
=> Update docker.md with more details and examples.

pkg/ha/ha_parser.go, pkg/ha/ha_parser_test.go, pkg/ha/ha_service.go, pkg/ha/mock_ha_service.go, pkg/ha/state.go, pkg/migrations/sql/preinstall/006-set_up_ha.sql
Iterate over ha to support multiple clusters in state & add a syncer … that syncs up HA state from DB
=> HA improvements support multiple prometheus cluster state 

pkg/ha/ha_parser_test.go, pkg/ha/ha_service.go, pkg/ha/mock_ha_service.go, pkg/ha/state.go
Change `map[string]*State` to `*sync.Map` & other improvemnts from review comments.
=> HA improvements- 2

docs/cli.md, pkg/pgclient/config.go, pkg/pgclient/config_test.go, pkg/util/lock.go
=> Adds support to make db-connection timeout configurable via CLI.

pkg/api/write.go, pkg/log/log.go, pkg/util/election.go
=> Fewer logging of non-leaders in debug log-level

pkg/pgmodel/common/extension/extension.go
=> fix to ignore mock* extension versions

pkg/pgmodel/ingestor/duplicates.go, pkg/pgmodel/ingestor/insert.go, pkg/pgmodel/metrics/metrics.go, pkg/util/util.go
=> Log once per metric table in case of a repetitive duplicate sample.

README.md, pkg/api/metrics.go, pkg/api/query.go, pkg/api/query_range.go, pkg/api/query_range_test.go, pkg/api/query_test.go, pkg/api/router.go, pkg/promql/engine.go
=> Consider metric evaluations in query endpoints & update PromQL engine namespace

pkg/pgmodel/migrate.go, pkg/runner/runner.go, pkg/util/lock.go
=> Improve logs when connector unable to migrate.

README.md, docs/bare-metal-promscale-stack.md
This doc is written in collaboration with @avthars to deploy Promscale, TimescaleDB & Prometheus on bare metal.
=> Add bare metal promscale stack deployment docs

pkg/util/util.go, pkg/util/util_test.go
=> Mask passwords with spaces

pkg/runner/client.go
=> Warn about low background workers when less than databases count.

docs/cli.md, pkg/pgclient/client.go, pkg/pgclient/config.go, pkg/pgclient/config_test.go, pkg/runner/runner.go, pkg/tests/end_to_end_tests/migrate_test.go
=> Adds support for including application_name in db connection string.

pkg/ha/ha_lock_client.go, pkg/ha/ha_parser.go, pkg/ha/ha_parser_test.go, pkg/ha/ha_service.go, pkg/ha/mock_ha_lock_client.go, pkg/ha/mock_ha_service.go, pkg/ha/state/state.go, pkg/pgclient/client.go, pkg/pgmodel/ingestor/ingestor.go, pkg/pgmodel/ingestor/parser.go, pkg/tests/end_to_end_tests/concurrent_sql_test.go, pkg/tests/end_to_end_tests/create_test.go, pkg/tests/end_to_end_tests/datasets_test.go, pkg/tests/end_to_end_tests/delete_test.go, pkg/tests/end_to_end_tests/drop_test.go, pkg/tests/end_to_end_tests/ha_check_insert_sql_test.go, pkg/tests/end_to_end_tests/ha_multiple_promscales_test.go, pkg/tests/end_to_end_tests/ha_single_promscale_test.go, pkg/tests/end_to_end_tests/ha_try_change_leader_sql_test.go, pkg/tests/end_to_end_tests/nan_test.go, pkg/tests/end_to_end_tests/promql_query_endpoint_test.go, pkg/tests/end_to_end_tests/query_integration_test.go, pkg/tests/end_to_end_tests/view_test.go, pkg/tests/upgrade_tests/upgrade_test.go, pkg/util/ticker.go
Also fixed bugs with:
- when 0 timestamp was sent as first in batch
sample was skipped
- state clone did not copy max time leader wrote
=> HA e2e tests

build/.goreleaser.yml, build/Dockerfile
=> Add ARM builds for docker

cmd/prom-migrator/README.md
=> Update prom-migrator readme

docs/gsoc/ideas_2021.md
=> GSoC 2021 idealist.

pkg/prompb/remote.pb.go, pkg/prompb/types.pb.go
This commit updates the Promb package till Feb 8, upto
cf269b7dddc3704d9fe6715dab09068f3c16e04e
=> Update Promb till Feb 8.

pkg/prompb/custom.ts.go, pkg/prompb/types.pb.go
This fixes a leak introduced in commit 4adc89 (PR #256).
=> Fix memory leak in Protobuf

pkg/api/write.go, pkg/api/write_test.go
=> Add tests to verify multiple JSON payloads support.

helm-chart/README.md, helm-chart/templates/deployment-connector.yaml, helm-chart/values.yaml
Add tolerations value to the Helm chart
=> Add tolerations to Helm chart

.github/workflows/docker-compose-tests.yml, .github/workflows/e2e.yml, .github/workflows/go-report-card.yml, .github/workflows/go-scheduled.yml, .github/workflows/go.yml, .github/workflows/gosec.yml
- Add the main branch as an alternative to master
- All workflows should run under force_test branch
- Run tests on release-* branches
=> Improve workflow ci files

go.mod, go.sum, pkg/pgclient/config.go, pkg/promql/bench_test.go, pkg/promql/engine.go, pkg/promql/engine_test.go, pkg/promql/functions.go, pkg/promql/test.go
Updates PromQL from upstream upto
6719071a0f12d2186b86edb61d3d3c477a932030 commit hash.
Comtains various PromQL optimizations and new PromQL functions.
=> Update promql till Match 19 commit 6719071

pkg/api/common.go, pkg/runner/flags_test.go
=> Fix: enable optional features in PromQL engine were not applied

cmd/prom-migrator/main.go
Signed-off-by: grzesuav <grzesuav@gmail.com>
=> fix: #553 - WriterAuth are ignored

pkg/api/router.go
=> Prevent crash with client does not send token when expected.

README.md, docs/bare-metal-promscale-stack.md, docs/binary.md, docs/configuring_prometheus.md, docs/docker.md
=> Document remote-write config params for most use-cases.

cmd/prom-migrator/main.go, cmd/promscale/main.go, pkg/pgclient/config.go, pkg/runner/args.go, pkg/runner/client.go, pkg/runner/runner.go, pkg/tests/end_to_end_tests/main_test.go, pkg/tests/end_to_end_tests/migrate_test.go, pkg/tests/upgrade_tests/upgrade_test.go, pkg/version/version.go
Added back changes from PR #546
=> rework - Add version flag to prom-migrator command

pkg/pgmodel/ingestor/buffer.go, pkg/pgmodel/ingestor/copier.go, pkg/pgmodel/ingestor/dispatcher.go, pkg/pgmodel/ingestor/ingestor.go, pkg/pgmodel/ingestor/ingestor_sql_test.go, pkg/pgmodel/ingestor/ingestor_test.go, pkg/pgmodel/ingestor/metric_batcher.go, pkg/pgmodel/model/interface.go
This is mostly a renaming/reorg refactor. There should not be any logic changes.
- handler->metric batcher
- insert -> copier
- inserter -> dispatcher
Constants are moved to the appropriate files.
Some dead code is removed.
=> Refactor ingest path

pkg/tests/end_to_end_tests/delete_test.go, pkg/tests/end_to_end_tests/zlast_test.go
=> Use small datasets for non-extended unit-tests.

cmd/promscale/main.go
=> -version flag exit code should be 0 not 1

build/Dockerfile
=> Fix cross platform docker

docs/cli.md, pkg/log/log.go, pkg/pgclient/client.go, pkg/pgclient/config.go, pkg/pgmodel/ingestor/copier.go, pkg/pgmodel/ingestor/dispatcher.go, pkg/pgmodel/ingestor/ingestor.go, pkg/tests/end_to_end_tests/concurrent_sql_test.go, pkg/tests/end_to_end_tests/create_test.go, pkg/tests/end_to_end_tests/delete_test.go, pkg/tests/end_to_end_tests/drop_test.go, pkg/tests/end_to_end_tests/insert_compressed_chunks_test.go, pkg/tests/end_to_end_tests/nan_test.go, pkg/tests/end_to_end_tests/null_chars_test.go, pkg/tests/end_to_end_tests/query_integration_test.go, pkg/tests/end_to_end_tests/view_test.go, pkg/tests/end_to_end_tests/zlast_test.go, pkg/tests/upgrade_tests/upgrade_test.go
=> Add support to reject samples if they fall on compressed chunks.

README.md
=> typo error in spelling

pkg/pgclient/client.go, pkg/pgclient/config.go, pkg/pgclient/config_test.go, pkg/runner/client.go
=> Fix DB URI issues for URIs with missing `?` parameter settings separator

README.md, docs/multi_tenancy.md
Signed-off-by: Harkishen Singh <harkishensingh@hotmail.com>
=> Docs for multi-tenancy.

go.sum, pkg/ewma/ewma.go, pkg/internal/testhelpers/containers.go, pkg/pgmodel/ingestor/dispatcher.go, pkg/pgmodel/ingestor/ingestor.go, pkg/pgmodel/ingestor/ingestor_sql_test.go, pkg/pgmodel/ingestor/watcher.go, pkg/pgmodel/model/interface.go, pkg/pgmodel/model/samples.go, pkg/pgmodel/model/sql_test_utils.go, pkg/pgmodel/querier/series_set_test.go, pkg/tests/upgrade_tests/upgrade_test.go
=> Warn on high ratio incoming outgoing rates.

pkg/api/parser/protobuf/protobuf.go
Reduces allocations significantly.
=> Buffer allocation pool for parsing protobuf

pkg/pgmodel/querier/query_builder.go
These function were actually supported in the extension before
but weren't being pushed down. This commit fixes that. 
Depends and is rebased on #666
=> Pushdown rate and increase optimizations

pkg/ha/filter.go, pkg/pgclient/client.go, pkg/pgmodel/metadata/metadata.go, pkg/pgmodel/model/sql_test_utils.go, pkg/pgmodel/querier/querier.go, pkg/pgmodel/querier/query_builder.go, pkg/pgxconn/pgx_conn.go, pkg/tests/end_to_end_tests/multi_tenancy_test.go, pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
Log time consumed by SQL queries in debug level & drop HA debug logs noise.
=> Log SQL queries & time consumed in debug level. 

pkg/api/query_test.go, pkg/pgclient/client_test.go, pkg/pgmodel/model/sql_test_utils.go, pkg/pgmodel/querier/querier.go, pkg/pgmodel/querier/querier_sql_test.go, pkg/pgmodel/querier/query_builder.go, pkg/pgmodel/querier/row.go, pkg/pgmodel/querier/series_set.go, pkg/pgmodel/querier/series_set_test.go, pkg/pgmodel/querier/timestamp_series.go, pkg/query/queryable.go
=> Mem optimizations on query path

pkg/tests/end_to_end_tests/prometheus_wal_test.go
This PR should fix the daily scheduled runner.
=> Fix: ingest real-dataset in Prometheus WAL.

README.md
=> Just a small docs correction about number of slack users

docs/prometheus_api.md
=> Mark Exemplar API as experimental in docs.

pkg/api/parser/json/json.go, pkg/api/parser/json/json_test.go
=> Fix: json-streaming push: do not reuse previous label pairs

helm-chart/values.yaml
=> Get rid of deprecated advisory log flags in helm.

pkg/pgmodel/common/extension/extension.go
We should support extensions set up at higher-versions
than what we would auto-upgrade to as long as they are
in the valid range.
Previously, we errored if the version was higher than expected.
But this isn't right. Users should be able to use extension versions
at the bleeding edge just fine (e.g. pre-release versions or versions
that are above the default version); we just shouldn't auto-upgrade
tp them. This fixes the logic to not error in such cases.
=> Support higher extension versions than auto-upgrade

docs/cli.md, pkg/api/common.go, pkg/api/router.go, pkg/query/query_engine.go, pkg/runner/flags.go, pkg/runner/flags_test.go, pkg/runner/runner.go, pkg/tests/end_to_end_tests/continuous_agg_test.go, pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go, pkg/tests/end_to_end_tests/query_integration_test.go
=> Add `-enable-feature=list,of,features` cli argument, use for tracing

helm-chart/values.yaml
The ergonomics of this suggestion are not great, so we've opened #918
to figure out how to improve this.
=> Add comment to helm chart about `-enable-feature=tracing`

pkg/tests/end_to_end_tests/functions_test.go
This is a test exposing broken functionality which was fixed in #958
=> Add test exposing broken _prom_catalog.metric_view() function

pkg/tests/end_to_end_tests/ha_check_insert_sql_test.go
=> Fix HA e2e test that contained a data race

CHANGELOG.md, deploy/helm-chart/README.md, deploy/helm-chart/templates/deployment-promscale.yaml, deploy/helm-chart/values.yaml
This is needed to allow setting environment variables and thus allow notifying that promscale was installed with tobs (part of https://github.com/timescale/tobs/issues/201).
=> deploy/helm-chart: add ability to set environment variables

go.mod, go.sum, pkg/api/metrics.go, pkg/api/query.go, pkg/api/query_range.go, pkg/api/query_range_test.go, pkg/api/query_test.go, pkg/api/read.go, pkg/api/read_test.go, pkg/jaeger/query/metrics.go, pkg/telemetry/metadata.go, pkg/telemetry/telemetry.go
This is a fix for wrong values in `os_version`, a bug in telemetry collection.
=> Fix os_version and add os_id in telemetry metadata.

docs/telemetry.md
Added documentation that explains what information is collected by usage telemetry
=> Add documentation for usage telemetry

docs/dataset.md
The dataset documentation assumed that the user is familiar with what the `dataset` is. This change introduces the `dataset` term.
=> Update dataset documentation

CHANGELOG.md, deploy/helm-chart/Chart.yaml, deploy/static/deploy.yaml, pkg/version/version.go
=> Prepare for the 0.8.0 release

pkg/version/version.go
Prepare for the next development cycle
- [-] CHANGELOG entry for user-facing changes
- [-] Updated the relevant documentation
=> Prepare for the next development cycle

deploy/helm-chart/templates/deployment-promscale.yaml
Part of fix for https://github.com/timescale/tobs/issues/226.
This is not a user-facing change nor it needs docs update.
=> deploy/helm-chart: allow templating extraEnv variables

CHANGELOG.md, deploy/helm-chart/Chart.yaml, deploy/static/deploy.yaml, pkg/version/version.go
=> Prepare for 0.9.0 release

.github/CODEOWNERS
I want to be notified when we update Go dependencies via dependabot.
=> Add Go dependency ownership to myself

pkg/pgmodel/querier/query_builder.go, pkg/pgmodel/querier/query_builder_samples.go, pkg/pgmodel/querier/query_sample.go, pkg/pgmodel/querier/row.go, pkg/promql/engine.go
When trying to understand the bug reported in https://github.com/timescale/promscale_extension/issues/72 I found
myself looking deeply into this code. It took a while to understand what we were actually doing, so I've tried to
document the mechanisms at play.
=> Add explanation and minor refactoring around pushdown functions

.goreleaser.yaml
As in title.
This would allow us to change release notes before publishing them.
=> *: add create release draft with goreleaser

deploy/helm-chart/templates/deployment-promscale.yaml
This allows to pass booleans and numeric types as `env` variable values in helm chart. By doing so we are fixing type casting issues in tobs.
=> deploy/helm: sanitize extra environment variables

.github/workflows/go-releaser.yml
Upload release file to pakagecloud 
- [ x ] CHANGELOG entry for user-facing changes
- [ x ] Updated the relevant documentation
=> Upload release to packagecloud

CHANGELOG.md
This PR updates the changelog to have an example tracing setup as part of unreleased, which was merged 8 days ago. See https://github.com/timescale/promscale/commit/309b9fd357213ec4e9e45f48db7e0825143daa90
=> Fix changelog: Add example tracing setup to unreleased.

CHANGELOG.md, deploy/helm-chart/Chart.yaml, deploy/static/deploy.yaml, pkg/version/version.go
=> Prepare for the 0.10.0 release.

CHANGELOG.md, docs/metrics.md, pkg/pgmodel/ingestor/copier.go, pkg/pgmodel/ingestor/dispatcher.go, pkg/pgmodel/ingestor/ingestor_sql_test.go, pkg/pgmodel/metrics/ingest.go
=> Register `promscale_ingest_channel_len` metric and make it a Gauge.

docs/multinode.md
`add_prom_node` is a procedure, so it must be invoked with `CALL`.
Closes #1010
=> Fix documentation around `add_prom_node`

.github/workflows/mixin.yml, Makefile
As in title. Adding a simple test to check if alerting rules are good syntax-wise.
=> *: add testing alert syntax in CI

CHANGELOG.md, docs/mixin/alerts/alerts.yaml, go.sum, pkg/pgclient/client.go, pkg/pgxconn/implement.go, pkg/pgxconn/pgx_conn.go, pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
Same as the title.
TODO
Note: This PR has a dependency on #1181. After that gets merged, alerts will be added as part of this PR.
=> Add database metrics, alerts and update the pgx implementation

.github/CODEOWNERS
I've recently deep dived on that code, so I would like to be in the loop on changes to it.
=> Add JamesGuthrie as owner of pgmodel/querier

pkg/pgmodel/ingestor/watcher.go
I don't like weird sentences 🤷 
=> Add missing word to slow ingestion warning

.github/renovate.json, .github/workflows/go-releaser.yml
Do not use `latest` version as it can silently break our CI pipeline. Instead opt to use released version and hand off handling of version update to renovate bot.
Follow-up to https://github.com/timescale/promscale/pull/1261
=> .github: finer control over used goreleaser version

.github/workflows/mixin.yml, Makefile, docs/mixin/dashboards/.lint, docs/mixin/dashboards/promscale.json
=> docs/mixin: add basic promscale dashboard

pkg/tests/end_to_end_tests/main_test.go
Fix Docker image typo in end-to-end tests
=> Fix Docker image typo in end-to-end tests

docs/compression-job-hotfix.md, docs/scripts/hotfix-compression-job-performance.sql, docs/scripts/rollback-hotfix-compression-job-performance.sql
Provide instructions to apply hotfix for compression job slow performance to Promscale
=> Add compression job performance hotfix instructions

pkg/tests/end_to_end_tests/trace_operation_calls_test.go, pkg/tests/testdata/expected/info_view-timescaledb.out, pkg/tests/testdata/expected/support.out, pkg/tests/upgrade_tests/upgrade_test.go
Use newly added trace_id custom type https://github.com/timescale/promscale_extension/pull/163
=> Use trace_id custom type

pkg/pgmodel/common/extension/extension.go, pkg/pgmodel/new_migrate.go
See https://github.com/timescale/promscale_extension/pull/182
- [ x ] CHANGELOG entry for user-facing changes
- [ x ] Updated the relevant documentation
=> Change extension schema to "public"

CHANGELOG.md, deploy/helm-chart/README.md, deploy/helm-chart/templates/deployment-promscale.yaml, deploy/helm-chart/templates/svc-promscale.yaml, deploy/helm-chart/values.yaml
Signed-off-by: Paweł Krupa (paulfantom) <pawel@krupa.net.pl>
As in title. Fixes https://github.com/timescale/promscale/issues/1241
=> deploy/helm-chart: remove openTelemetry.enabled option

cmd/prom-migrator/README.md
=> Add note saying `prom-migrator` cannot migrate to HA setups.

CHANGELOG.md, docs/dataset.md
With the latest changes to dataset configuration, some documentation was slightly outdated.
=> Minor cleanups of dataset documentation

.github/CODEOWNERS, .github/workflows/helm.yml, .github/workflows/mixin.yml, Makefile, deploy/helm-chart/templates/prometheus-rule.yaml, deploy/static/deploy.yaml, docs/mixin/.gitignore, docs/mixin/.lint, docs/mixin/Makefile, docs/mixin/README.md, docs/mixin/alerts/alerts.libsonnet, docs/mixin/config.libsonnet, docs/mixin/dashboards/dashboards.libsonnet, docs/mixin/mixin.libsonnet
This PR is making `docs/mixin` directory a self-contained package. It is also adding jsonnet wrapper around mixin and improving documentation
=> docs/mixin: jsonnetify mixin to allow using common mixin tooling

pkg/version/version.go
=> Support pre-release versions of 0.5.0

pkg/tests/upgrade_tests/shapshot.go
The general way that `diff a b` works is to show changes which were made
to `a` to get to `b`. In PrintDbSnapshotDifferences this was the
opposite, which made interpreting the result confusing.
Additionally, the diff missed schemas which were in `b`, but not `a`.
=> Improve upgrade test output

pkg/jaeger/query/trace_query.go, pkg/jaeger/query/trace_scan.go, pkg/pgmodel/ingestor/trace/tag_batch.go, pkg/pgmodel/ingestor/trace/tag_batch_test.go, pkg/tests/end_to_end_tests/functions_test.go
=> Fixes for new tag_map type

deploy/helm-chart/Chart.yaml, deploy/static/deploy.yaml, pkg/version/version.go, scripts/end_to_end_tests.sh
=> Prepare for the 0.11.0-alpha release

deploy/helm-chart/README.md, deploy/helm-chart/templates/config.yaml, deploy/helm-chart/templates/deployment-promscale.yaml, deploy/helm-chart/values.yaml, deploy/static/deploy.yaml, docker-compose/docker-compose.yaml, docker-compose/high-availability/docker-compose.yaml, docker-compose/test.sh
This is allowing to configure promscale via configuration file and fixes issues with incorrectly setting dataset config values.
=> deploy/helm-chart: properly set dataset configuration

deploy/helm-chart/Chart.yaml, deploy/static/deploy.yaml, pkg/version/version.go
=> Prepare for the 0.11.0-alpha.1 release

pkg/api/router.go, pkg/jaeger/api.go, pkg/jaeger/query/config.go, pkg/jaeger/query/find_trace_ids.go, pkg/jaeger/query/find_traces.go, pkg/jaeger/query/get_trace.go, pkg/jaeger/query/query.go, pkg/jaeger/query/trace_query.go, pkg/runner/flags.go, pkg/runner/runner.go, pkg/tests/end_to_end_tests/ingest_trace_test.go, pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go, pkg/tests/end_to_end_tests/trace_query_integration_test.go
The config object will be needed to specify the max
trace duration the query can expect.
=> Optimize tracing query through max trace duration

deploy/helm-chart/Chart.yaml, deploy/static/deploy.yaml, pkg/version/version.go
=> Prepare the 0.11.0-alpha.2 release

pkg/pgmodel/common/extension/extension.go
=> Fix output of skipped extension prerelease information

docs/configuration.md, pkg/rules/config.go
=> Update -metrics.rules.prometheus-config -> -metrics.rules.config-file

deploy/helm-chart/Chart.yaml, deploy/static/deploy.yaml, pkg/version/version.go
=> Prepare 0.11.0-alpha.3

CHANGELOG.md, deploy/helm-chart/Chart.yaml, deploy/static/deploy.yaml, docs/docker.md, pkg/version/version.go
=> Prepare for the 0.11.0 release

docs/binary.md, docs/docker.md
=> Fine-tune installation documentation

docker-compose/docker-compose.yaml, docker-compose/high-availability/docker-compose.yaml, scripts/end_to_end_tests.sh
- Use `timescale/timescaledb-ha` docker image
- Remove `startup.upgrade-prerelease-extensions`
=> Post release clean up

migration-tool/cmd/prom-migrator/README.md
Direct users to our Slack or forum for questions and feedback
=> Direct users to our Slack or forum for questions and feedback

docs/data-model.md
On a number of occasions I have wanted concise documentation of the metric data storage. This is it.
=> Add documentation of Promscale metric data model

.github/workflows/helm.yml
Unlocking version to align with documentation.
=> .github: always use latest timescaledb in helm tests

pkg/internal/testhelpers/postgres_container.go, pkg/tests/upgrade_tests/upgrade_test.go
In version 0.11.0 we introduced a hard dependency on the promscale
extension at version 0.5.0. Additionally, we renamed some flags in
0.10.0, and dropped support for the old flags in 0.11.0.
This change adds logic to the upgrade tests to work around these two
facts.
=> Fix upgrade tests around version 0.11.0

CHANGELOG.md, pkg/rules/config.go, pkg/runner/runner.go, pkg/telemetry/telemetry.go
Fixes: https://github.com/orgs/timescale/projects/30/views/38
=> Adds support for telemetry for alerting and recording rules.

pkg/tests/end_to_end_tests/alerts_test.go
=> Fix var assignment in E2E tests.

pkg/internal/testhelpers/postgres_container.go
When we run the upgrade tests, we purposefully initialize a database
with an old timescale docker image, containing an old timescaledb
version. We then start a new version of the timescale docker image with
the same data.
If the old timescaledb version is not present in the new container, then
this can cause problems if we don't immediately run
`ALTER EXTENSION timescaledb UPDATE`.
This change updates timescaledb in all databases of the timescale
container immediately on startup.
Closes #1433
=> Automatically update the timescaledb extension in tests

.github/renovate.json
Replace manual version bumps (like: https://github.com/timescale/promscale/pull/1423) with automation :)
=> .github: manage extension version bumps via renovate

.github/workflows/go.yml, Makefile, docker-compose/high-availability/test.sh, docker-compose/test.sh, docs/scripts/install-crontab.sh, docs/scripts/prom-execute-maintenance.sh, scripts/end_to_end_tests.sh, scripts/generate-deploy-script.sh, scripts/wait-for.sh
Looks like our `master` build is broken partially due to incorrect shell script:
```
./scripts/end_to_end_tests.sh: line 56: CONN_PID: unbound variable
```
This PR is meant to implement a CI check to prevent similar issues in the future and fix current ones.
=> .github/workflows: add shellcheck GH action

CHANGELOG.md, deploy/helm-chart/Chart.yaml, deploy/static/deploy.yaml, pkg/version/version.go
=> Release 0.12.1

CHANGELOG.md, pkg/pgmodel/migrate.go, pkg/pgmodel/new_migrate.go, pkg/tests/end_to_end_tests/new_migrate_test.go
The table could exist in any schema. We expect there to be either 0 or 1
tables. If there are more then something really weird has happened, and
we can't safely proceed.
Part of: https://github.com/timescale/promscale_extension/issues/371
=> Refine check for existence of `prom_schema_migrations` table

ct.yaml, deploy/helm-chart/Chart.yaml
=> *: align helm chart maintainers with kubernetes-timescaledb charts

.github/CODEOWNERS
As there is now a dedicated team for this area, and the work that they are doing is a bit far from my day-to-day, I'd prefer not to be a code owner.
=> Remove JamesGuthrie as codeowner of /deploy

CHANGELOG.md, pkg/rules/config.go, pkg/rules/rules.go, pkg/rules/rules_test.go, pkg/rules/testdata/rules.glob.config.yaml, pkg/rules/testdata/rules_dir/rule.one.yaml, pkg/rules/testdata/rules_dir/rule.two.yaml, pkg/tests/end_to_end_tests/alerts_test.go, pkg/tests/end_to_end_tests/rules_test.go
Fixes: https://github.com/timescale/o11y-team-applications/issues/206
TODO: Update the changelog after `0.12.0` is out.
=> Implement support for glob in rule_files.

pkg/rules/adapters/ingest.go, pkg/rules/rules.go
This PR fixes a unit test that got bad due to rebase.
=> Do not check for ingestor in ingestAdapter.

pkg/tests/end_to_end_tests/trace_query_integration_test.go
The test occasionally fails with:
```
Received unexpected error:
http get: Get "http://localhost:9201/api/services": dial tcp [::1]:9201: connect: connection refused
```
The server listen and client connect, which run in separate goroutines,
race against one another. Occasionally, the client connect is faster
than the server listen, causing the above error.
By moving the call to `net.Listen` out of the goroutine, we ensure that
both threads of execution must wait on the socket listen to complete
before proceeding, eliminating the race.
=> Fix flaky test `TestCompareTraceQueryResponse`

deploy/helm-chart/templates/_helpers.tpl, deploy/helm-chart/templates/config.yaml, deploy/helm-chart/templates/deployment-promscale.yaml, deploy/helm-chart/templates/prometheus-rule.yaml, deploy/helm-chart/templates/secret-connection.yaml, deploy/helm-chart/templates/service-account.yaml, deploy/helm-chart/templates/service-monitor.yaml, deploy/helm-chart/templates/svc-promscale.yaml, deploy/static/deploy.yaml, scripts/generate-helm-alerts.sh
Change Kubernetes object names to be more consistent
=> Consistent naming scheme

README.md
Adding the new quick start at the top of the README to guide folks to give the product a try.
=> Add quick start to README

pkg/clockcache/cache.go, pkg/clockcache/cache_bench_test.go
It seems as though the existing benchmarks cannot be used to measure the
effect of false sharing, so I added a new benchmark.
=> Add BenchmarkCacheFalseSharing

CHANGELOG.md, pkg/tests/upgrade_tests/upgrade_test.go, pkg/version/version.go
=> Prepare for the 0.14.0 development cycle

CHANGELOG.md, deploy/helm-chart/templates/deployment-promscale.yaml, deploy/helm-chart/values.schema.json, deploy/helm-chart/values.yaml
Schema was generated using https://jsonschema.net/. More information
on schema generation can be found in https://www.arthurkoziel.com/validate-helm-chart-values-with-json-schemas/
*Note: If your PR involves benchmarks, you can run the `Benchmarks` workflow by adding `action:benchmarks` label. The PR must be opened from Promscale branch so that Github actions can leave a comment comparing results against `master`.*
=> deploy/helm-chart: add schema for input validation

pkg/tests/end_to_end_tests/ingest_trace_test.go
*Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Linking an issue can be done by mentioning a key word (`closes #111`, `fixes #222`, `resolve #333`) or manually on github.com, even after the pull request is created.*
*Note: If your PR involves benchmarks, you can run the `Benchmarks` workflow by adding `action:benchmarks` label. The PR must be opened from Promscale branch so that Github actions can leave a comment comparing results against `master`.*
=> Use test table in Trace Ingestion tests

go.mod, go.sum
A user has reported a regression and it is suspected that upgrading pgx may solve it.
https://github.com/timescale/promscale/issues/1573
=> upgrade pgx dependencies

CHANGELOG.md, deploy/static/deploy.yaml, pkg/version/version.go
Reference: https://github.com/timescale/promscale/pull/1507
=> Prepare for the 0.14.0 release.

pkg/pgmodel/Readme.md, pkg/pgmodel/ingestor/copier.go, pkg/pgmodel/ingestor/dispatcher.go, pkg/pgmodel/ingestor/ingestor.go, pkg/pgmodel/ingestor/metric_batcher.go
When working on some changes to the caches, I found that the existing
documentation of the write path is somewhat out of date, and not 1:1
comparable to the existing code.
=> Rework ingest pipeline documentation

pkg/pgmodel/ingestor/trace/trace_dispatcher.go
In order to properly capture error for async ingest we need to wait for async request to complete before reporting metrics.
=> Track errors for async trace ingest

CHANGELOG.md, docker-compose/docker-compose.yaml
Run timescaledb-tune with the promscale profile in docker compose.
=> Run timescaledb-tune with the promscale profile

docker-compose/jaeger-promscale-demo/README.md, docker-compose/jaeger-promscale-demo/docker-compose.yaml
This demo is based on https://github.com/jaegertracing/jaeger/tree/main/examples/hotrod
Fixes https://github.com/timescale/promscale/issues/1545
*Note: If your PR involves benchmarks, you can run the `Benchmarks` workflow by adding `action:benchmarks` label. The PR must be opened from Promscale branch so that Github actions can leave a comment comparing results against `master`.*
=> demo: grpc based remote storage for jaeger collector

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
**Bug Request Template**:
--------------------------------------
**Feature Request Template:**
---------------------------------------
=> Add Bug/Feature templates

pkg/pgmodel/lreader/labels_reader.go, pkg/pgmodel/lreader/labels_reader_test.go
=> Filter by label key before Exists() for LabelValues() in multi-tenancy mode

pkg/tests/upgrade_tests/upgrade_test.go
Add a metric that isn't compressed for upgrade tests
Test for issue https://github.com/timescale/promscale_extension/issues/504
=> Add test for upgrades with no compression

docs/runbooks/PromscaleCompressionLow.md, docs/runbooks/PromscaleMaintenanceJobFailures.md, docs/runbooks/PromscaleMaintenanceJobRunningTooLong.md
=> Add required parameter to `config_maintenance_jobs` examples

pkg/pgmodel/lreader/labels_reader.go, pkg/pgmodel/lreader/labels_reader_test.go, pkg/pgmodel/model/sql_test_utils.go
Prevent multiple series scans when there are multiple valid tenants.
=> Optimize label queries with tenants

CHANGELOG.md, docs/mixin/dashboards/promscale.json, pkg/pgmodel/metrics/database/metrics.go, pkg/util/metrics.go
Adding two more metric types from #492
=>  Metrics for long-running statements and locks originating from maintenance jobs

pkg/version/version.go
This is a prerequisite to being able to release the extension.
=> Allow using version 0.7.0 of the extension

.github/workflows/go-scheduled.yml
=> Remove last bit of helm pieces

migration-tool/cmd/prom-migrator/README.md
=> Docs: Use thanos-remote-read adapter for prom-migrator

CHANGELOG.md, docs/mixin/alerts/alerts.yaml
This allows for better alert routing and silencing in kubernetes environments. In environments where `namespace` label is not added to metrics, this does nothing.
=> docs/mixin: group alerts by namespace

docs/mixin/dashboards/promscale.json
=> Promscale dashboard: Use rate in `Cache hit ratio` panel

pkg/tests/end_to_end_tests/continuous_agg_test.go, pkg/tests/end_to_end_tests/create_test.go, pkg/tests/end_to_end_tests/query_integration_test.go
Signed-off-by: Harkishen-Singh [harkishensingh@hotmail.com](mailto:harkishensingh@hotmail.com)
Relates https://github.com/timescale/promscale_extension/pull/554
=> Update tests related to `register_metric_view()`

pkg/vacuum/vacuum.go
Exposes three new prometheus metrics in the vacuum engine so we can more easily observe its behavior
* adds a gauge for the number of tables left to vacuum
* adds a counter for the number of tables vacuumed
* adds a gauge that roughly tracks the number of database connections currently in use by the vacuum engine
Since we limit our query to 1000 results, the `tables left to vacuum` gauge will never go above 1000 even if there are many more tables to be vacuumed.
#1754
=> Add prometheus metrics to vacuum engine

docs/dataset.md
=> Update dataset config migration guide

pkg/pgmodel/metrics/database/database.go, pkg/pgmodel/metrics/database/metric_series.go, pkg/pgmodel/metrics/database/metrics.go
=> Adds support to instrument metric-rollups behaviour

pkg/pgmodel/metrics/database/metrics.go
=> Stop counting idle processes in metrics

pkg/version/version.go
=> Preparing for 0.8.0 extension release

pkg/api/metrics.go, pkg/api/query.go, pkg/api/router.go, pkg/jaeger/store/store.go, pkg/pgmodel/metrics/query.go
We [discussed about it](https://github.com/timescale/promscale/pull/1806/files#r1062452667) and agreed to change it to improve readability 
=>  Rename err label to reason

.github/workflows/go-e2e.yml, .github/workflows/integration.yml, CHANGELOG.md, Makefile, docker-compose/docker-compose.yaml, docker-compose/high-availability/docker-compose.yaml, docker-compose/jaeger-promscale-demo/docker-compose.yaml, docker-compose/promscale-demo/docker-compose.yaml, pkg/version/version.go
=> Add support for PG15

pkg/runner/client.go
skip apply dateset config when read only, resolve https://github.com/timescale/promscale/issues/1796
=> skip apply dateset config when read only

README.md
=> Add note about Promscale being discontinued
