helm-chart/README.md
helm-chart/templates/cronjob-dropchunk.yaml
helm-chart/templates/deployment-connector.yaml
helm-chart/values.yaml

This PR updates the README to document all the configurable
values in the chart along with re-introducing templating for the
secret that should contain the db password.
The CronJob schedule is now also configurable.

Enable templating the password secret and write a proper README

---

pkg/pgclient/client.go
pkg/pgmodel/ingestor.go
pkg/pgmodel/ingestor_test.go
pkg/pgmodel/pgx.go
pkg/pgmodel/pgx_test.go

Prof numbers indicate we're spending an inordinate amount of time in
selectgo trying to determine which channels to access; mostly in a
single select in CopyFrom. This commit improves performance by reducing
the number of goroutines in play at once, and the number of times that
select can be accessed.
Instead of having a single goroutine per-metric, we now have a fixed
number of them, equal to the GOMAXPROCS, and we hash metric table names
to determine which goroutine is responsible for each insert. The
inserters maintain a set of pending inserts, and they flush the values
to the database if:
a. the amount of pending writes for that metric becomes large enough
b. a sufficient amount of time has elapsed since we received the
first sample in a metric's batch
c. if the inserter runs out of …

Improve performance by reducing goroutines

---

pkg/pgmodel/pgx.go

This was missed in the switch from casting after retrieval to casting
during.

Check that elements exist before casting.

---

pkg/pgmodel/pgx_test.go
pkg/pgmodel/query_builder.go
pkg/pgmodel/query_integration_test.go

Some queries returned wrong results because of defined SQL query logic
conditions. There was also an error in the empty regex matcher anchoring
logic which caused wrong results to be returned.

Fix query result mismatches versus Prometheus

---

README.md
helm-chart/README.md
helm-chart/templates/cronjob-dropchunk.yaml
helm-chart/templates/deployment-connector.yaml
helm-chart/values.yaml
pkg/pgclient/client.go

The flag names are changed to signify that the connector is no longer 
compatible with Postgres, just TimescaleDB.
Also the deployment in the helm-chart is simplified to use
the TS_PROM environment variables to set the connection
flags.
*Warning* Upon merging, the helm chart will require a new docker build to be uploaded to the docker hub because it assumes the new flag names

Update the flag names and default value of the dbname flag

---

docker-compose.yml

This PR fixes the environment variable names in docker-compose.yml example setup for the v0.1.0-alpha.2.

Fix docker compose example for 0.1.0-alpha.2

---

pkg/internal/testhelpers/containers.go
pkg/internal/testhelpers/containers_test.go
pkg/pgmodel/query_integration_test.go

Setting the read-only mode on the test database ensures we are not
writing to the database when executing queries.

Set query integration tests to read-only mode

---

pkg/internal/testhelpers/containers.go
pkg/internal/testhelpers/containers_test.go
pkg/pgmodel/migrate_test.go
pkg/pgmodel/nan_test.go
pkg/pgmodel/query_integration_test.go
pkg/pgmodel/sql_bench_test.go
pkg/pgmodel/view_test.go
pkg/util/election_test.go

Some of the SQL functions are suspected to be very performance
intensive. Adding the benchmark allows us to setup a baseline for future
performance testing.
Note: `BenchmarkKeyValueArrayToLabelArrayExistingLabels` fails to run, we need to take a look at it. I might have hit a bug with the benchmark.

Add Go benchmarking for certain SQL functions

---

pkg/log/log.go
pkg/pgclient/client.go
pkg/pgmodel/bigcache.go
pkg/pgmodel/pgx.go

Default caching logger would output logs to standard output which did not conform
to our logging library output standards. This commit adds a custom logger which
transforms that output to match our logger.
Closes #52

Add custom logger to caching layer

---

cmd/timescale-prometheus/main.go

Adding a namespace will give our fully qualified metric names a prefix so they don't look so generic.
For example, `current_leader` will turn into `ts_prom_current_leader`.
This PR also registers already defined query path metrics.

Add Prometheus namespace and register missing metrics

---

helm-chart/templates/deployment-connector.yaml
helm-chart/values.yaml

Annotations predefined by the Prometheus Helm chart (https://hub.helm.sh/charts/stable/prometheus)
are needed in the pod annotations so that the Prometheus service discovery works properly with
the connector and scrapes up its metrics endpoint.

Added Prometheus annotations to Helm chart

---

pkg/internal/testhelpers/containers.go

testcontainers.wait.ForSQL strategy is used to wait for the
success of `SELECT 1` on the database container.

Make sure db is accepting connections in container for itests

---

extension/Makefile

This allows other tools (the timescaledb-docker-ha images for example)
to build this against pg11 for example.

Reuse variables if they are already set

---

extension/Readme.md
extension/sql/timescale-prometheus.sql

The extension requires that the schema for timescale-prometheus
connector installed and the migration is run. We add a check so
that the extension let's people know if something is wrong.

Add Prerequisite check for timescale-prometheus-extra

---

extension/sql/timescale-prometheus.sql
extension/src/support.c

Previously a support function only optimized function calls
on consts but the operator logic inserts a CoerceToDomain
node before the const as well. This PR allows this case to
also be handled by relaxing the constrainst on args from having
to be constants to having to be merely const-like. That is
the expression cannot reference any vars or use volatile functions.

Fix support function to work with operators

---

helm-chart/Chart.yaml
pkg/pgmodel/end_to_end_tests/migrate_test.go
pkg/pgmodel/migrate.go

Previously migrations failed if they were run on an already migrated database.
This made the connector fail if it was ever restarted.

Make migrations idempotent

---

helm-chart/templates/cronjob-dropchunk.yaml

The `prom` schema does not exist anymore. It is replaced by `prom_api`.
cf. Issue #83  for more context.

Fix the cronjob call

---

Dockerfile
cmd/timescale-prometheus/main.go
cmd/timescale-prometheus/version_info.go
docker-compose.yml
pkg/log/log.go
pkg/util/election.go
pkg/util/lock.go

When debugging issues that users are facing we need to know
which version they are using. Especially in container environments 
because of stale :latest images.

Add version const and print on boot

---

pkg/internal/testhelpers/containers.go
pkg/internal/testhelpers/containers_test.go
pkg/pgmodel/end_to_end_tests/main_test.go
pkg/util/election_test.go

Just like it says in the title. Add
```
-print-logs true
```
to print the postgres logs in the `end_to_end` tests

Add option to output postgres log, and clean docker image when done

---

pkg/pgclient/client.go
pkg/pgmodel/pgx.go

This commit switches the way we do inserts into the database. Instead
of each InsertHandler running CopyFrom directly when it finishes a
batch of data, it instead forwards the values to a pool of CopyFrom
workers, who perform the actual insertion. This is intended to provide
a few advantages:
1. If one metric is very hot, it will be able to continue
processing new data at the same time as earlier values are
inserted. Before this commit, individual metrics would experience
head-of-line blocking in such cases.
2. This may allow a single worker to handle all inserts in the event
that the insert-rate is low enough.
3. This should ease experimentation with batching across metrics.

Switch to dedicated CopyFrom workers

---

pkg/api/query.go
pkg/pgmodel/end_to_end_tests/promql_endpoint_integration_test.go
pkg/pgmodel/end_to_end_tests/query_integration_test.go

Integration tests are performed by checking the results of the new endpoints
against the results from a Prometheus instance that has ingested the same
dataset. It tests most of the PromQL queries, its aggregators and functions.

Add integration tests for PromQL query and query_range endpoints

---

pkg/pgmodel/labels.go

The labels set was put in the interner in the wrong location, so it
could be read before it's fully written. This commit fixes it.

Fix race condition on labels

---

extension/src/lib.rs
pkg/pgmodel/end_to_end_tests/functions_test.go

Looks like we misunderstood construct_md_array, it needs to have an elem
for every slot in the array regardless of rather it's NULL (we had
thought it only needed non-NULL elements). This commit fixes this
oversight.

Fix pushdown array construction

---

go.mod
pkg/api/query.go
pkg/api/query_range.go
pkg/api/query_range_test.go
pkg/api/query_test.go
pkg/pgmodel/end_to_end_tests/query_integration_test.go
pkg/pgmodel/migrate.go
pkg/pgmodel/pgx.go
pkg/pgmodel/pgx_test.go
pkg/pgmodel/querier.go
pkg/pgmodel/querier_test.go
pkg/pgmodel/query_builder.go
pkg/pgmodel/series_set.go
pkg/promql/bench_test.go
pkg/promql/engine.go
pkg/promql/engine_test.go
pkg/promql/functions.go
pkg/promql/functions_test.go
pkg/promql/fuzz.go
pkg/promql/promql_test.go
pkg/promql/quantile.go
pkg/promql/query_logger.go
pkg/promql/query_logger_test.go
pkg/promql/test.go
pkg/promql/test_test.go
pkg/promql/value.go
pkg/query/query_engine.go
pkg/query/queryable.go

This PR Pushes some query processing logic from the PromQL engine into the database.
We modify the interaction between the query engine and the storage layer so that the storage layer now takes in the node-branch it's evaluating, and computes as much of the branch as it's capable of, returning the top-most node it computed. The engine then walks up the execution path, starting at that node, and performs the remainder of the computation.
This PR puts in the framework to accomplish this and tests it with one pushdown function `delta`, which serves as a proof of concept. Further PRs will be used to push down other functions and processing nodes.
The approach used here is limited in certain ways:
1) It is not meant to push down past branches that split. This may or may not be fundamental but …

Add promql endpoint pushdown

---

pkg/api/metrics.go

Reference: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
Closes #140

Alignment fix for atomically accessed fields on 32-bit systems

---

extension/Cargo.lock

Update rust libraries. Most notably this removes the implicit guard_pg
from the postgres-function macros.

Update rust libraries

---

pkg/clockcache/Readme.md
pkg/clockcache/cache.go
pkg/clockcache/cache_bench_test.go
pkg/clockcache/cache_test.go

We have a number of places in the connector where we want to store a
cache of elements. Our expectation is that the set of live elements
will be time-correlated, and therefore, when we want to evict elements
from the cache the least-recently-used element is the one least likely
to be used again in the future. There for this commit adds an LRU
implementation suitable for use in such caches. Traditional LRUs suffer
from large amounts of contention in multi-threaded workloads, so we use
a CLOCK-based approximate LRU; more information can be found in the
README.

Add CLOCK based approximate LRU

---

README.md
cmd/timescale-prometheus/main.go
docs/prometheus_api.md
go.mod
go.sum
pkg/api/health.go
pkg/api/label_values.go
pkg/api/labels.go
pkg/api/labels_test.go
pkg/api/query.go
pkg/api/query_range.go
pkg/api/query_range_test.go
pkg/api/query_test.go
pkg/internal/testhelpers/PromTestDockerfile
pkg/internal/testhelpers/containers.go
pkg/pgmodel/end_to_end_tests/main_test.go
pkg/pgmodel/end_to_end_tests/migrate_test.go
pkg/pgmodel/end_to_end_tests/promql_endpoint_integration_test.go
pkg/pgmodel/end_to_end_tests/query_integration_test.go
pkg/pgmodel/pgx.go
pkg/pgmodel/pgx_test.go
pkg/pgmodel/querier.go
pkg/pgmodel/querier_test.go
pkg/pgmodel/series_set_test.go
pkg/query/queryable.go

The LabelNames and LabelValues endpoints are required
so timescale-prometheus can be directly queried by Grafana.
Not all metadata endpoints are implemented as a
prometheus server has (the series  and metadata endpoints
are missing) but they are never queried by Grafana.
An http router is added to handle path params and scale
better than the default multiplexer under load

Implement promql meta endpoints

---

pkg/clockcache/cache.go
pkg/pgclient/client.go
pkg/pgmodel/end_to_end_tests/nan_test.go
pkg/pgmodel/end_to_end_tests/promql_endpoint_integration_test.go
pkg/pgmodel/end_to_end_tests/query_integration_test.go
pkg/pgmodel/labels.go
pkg/pgmodel/pgx.go
pkg/pgmodel/pgx_test.go
pkg/pgmodel/query_builder.go
pkg/pgmodel/series_set.go
pkg/pgmodel/series_set_test.go

In simple queries, approximately 1/3rd our queries runtime is spent in
key_value_array. To reduce the time spent, this commit adds a cache of
ids-to-labels in the connector, so we can only fetch those labels we
have never seen before.

Add label cache, and only fetch missing labels at query time 

---

pkg/api/write.go
pkg/pgmodel/end_to_end_tests/concurrent_sql_test.go
pkg/pgmodel/end_to_end_tests/create_test.go
pkg/pgmodel/end_to_end_tests/drop_test.go
pkg/pgmodel/end_to_end_tests/nan_test.go
pkg/pgmodel/end_to_end_tests/query_integration_test.go
pkg/pgmodel/end_to_end_tests/view_test.go
pkg/pgmodel/ingestor.go

Fix a bug in the ingestor which could cause data corruption as samples were readded to the WriteReq pool before they were written to the DB. With this commit we can re-enable the pool. Actually using the pool gives a 10% speedup.

Reenable the WriteRequest pool, fixing data corruption

---

pkg/pgmodel/pgx.go

Logs the detail of the pg error, which will include the time and
series id of the duplicate.

Better log message when encountering duplicate

---

cmd/timescale-prometheus/main.go

Otherwise it cannot be queried

Add /metrics to our custom mux

---

pkg/api/common.go
pkg/api/query.go
pkg/api/series.go
pkg/pgmodel/end_to_end_tests/promql_endpoint_integration_test.go
pkg/pgmodel/end_to_end_tests/query_integration_test.go
pkg/pgmodel/query_builder.go

When start/end timestamp values are not sent to a query, Prometheus sets them
min/max timestamp values. These values are outside of Prometheus date/time
ranges and cause errors when used in SQL queries. This fix limits those values
to year 1970 for min and year 3000 for max.
Closes #125

Fix for min/max start/end timestamp values for remote read

---

pkg/pgmodel/end_to_end_tests/query_integration_test.go
pkg/pgmodel/sql_reader.go

Our labels were too well behaved; the order in which we queried them
was always the order they were stored. This adds another label to
ensure that there's some noise in how we query.

Update tests to detect labels issue

---

cmd/timescale-prometheus/main.go
pkg/api/common.go
pkg/api/common_test.go
pkg/api/label_values.go
pkg/api/labels.go
pkg/api/labels_test.go
pkg/api/query.go
pkg/api/query_range.go
pkg/api/query_range_test.go
pkg/api/query_test.go
pkg/api/read.go
pkg/api/series.go
pkg/api/series_test.go
pkg/pgmodel/end_to_end_tests/promql_endpoint_integration_test.go

A flag can be set by the user to specify the allowed
origins to access the HTTP API. A wrapper handler
sets the proper CORS headers if the flag is enabled.

Add proper CORS handling by the HTTP API

---

pkg/pgmodel/query_builder.go
pkg/pgmodel/series_set.go
pkg/pgmodel/series_set_test.go
pkg/pgmodel/sql_reader.go
pkg/pgmodel/sql_test.go
pkg/pgmodel/sql_utils.go

Keeping around a `pgx.Rows` is dangerous, as doing so keeps a lock on the underlying connection. This means that the connecter can self-starve if it gets partway through a Rows and decides it needs to fetch more data from the database. To fix this, this commit materializes all `pgx.Rows` into a `[]timescaleRow` as soon as possible.
(Further, It looks like there's no guarantee that a `SeriesSet` will be read until the end anyway)
This commit also refactors the `TestPGXQuerierQuery` test, as updating the old version to the new code was too onerous, and batches multi-metrics queries together, as I was rewriting that code anyway. It seems to give a nice performance increase.

Fix connection leaks

---

README.md
docs/binary.md
docs/docker.md
docs/sql_schema.md

The goal of this commit is to streamline our documentation.
Namely we wanted to:
- Make instructions for various installation methods more streamlined.
We now show all installation methods in one place in the README
with links to more detailed instructions.
- Docker and Binary instructions become more complete and self-contained
at the cost of some duplication.
- Make the main README shorter and more to-the-point
- Make the links to the SQL stuff more prominent and easy to find.
Some of this is done but more can be done later.

Improve documentation

---

cmd/timescale-prometheus/main.go
pkg/api/health_test.go
pkg/api/metrics.go
pkg/api/read.go
pkg/api/read_test.go
pkg/api/write.go
pkg/api/write_test.go
pkg/pgmodel/end_to_end_tests/promql_write_endpoint_test.go

Validate some HTTP headers when receiving a remote request to prevent unmarshalling of irrelevant data.

Validate Request headers

---

helm-chart/README.md
helm-chart/templates/deployment-connector.yaml
helm-chart/values.yaml

Based on #224 I think timescale-prometheus now respects `TS_PROM_DB_SSL_MODE`? (And the config option was already in the helm chart.) I haven't looked too deeply honestly, so it might not even be configurable yet.

Add ssl mode config option

---

cmd/timescale-prometheus/main.go
cmd/timescale-prometheus/main_test.go
pkg/api/metrics.go
pkg/api/router.go
pkg/api/router_test.go
pkg/pgclient/client.go
pkg/pgclient/metrics.go
pkg/pgmodel/end_to_end_tests/functions_test.go
pkg/pgmodel/end_to_end_tests/promql_endpoint_integration_test.go
pkg/pgmodel/end_to_end_tests/promql_label_endpoint_test.go
pkg/pgmodel/end_to_end_tests/promql_query_endpoint_test.go
pkg/pgmodel/end_to_end_tests/promql_series_endpoint_test.go
pkg/pgmodel/end_to_end_tests/promql_write_endpoint_test.go
pkg/pgmodel/metrics.go

Moving the router and metrics to separate package outside of main package
enables us to reuse it for our end-to-end tests and use the main router for
testing.
Closes #206

Move router and metrics to api package

---

pkg/api/write.go
pkg/util/election.go

The test for eligibility for leader election is based on how long it's been since the client has received a WriteReq from prometheus. Therefore we need to record this time even if the client is not the leader.

Fix leader election

---

cmd/timescale-prometheus/main.go
cmd/timescale-prometheus/main_test.go
pkg/pgclient/client.go
pkg/pgmodel/end_to_end_tests/migrate_test.go
pkg/pgmodel/migrate.go
pkg/runner/runner.go
pkg/runner/runner_test.go
pkg/util/election_test.go
pkg/util/lock.go

Prior to this commit migration was gated on leader election. This had
three issues:
1. Multiple writers that did not engage in leader-election would race
to migrate the database.
2. Read-only connectors would not check that the database was at a
valid version
3. There was nothing preventing the database from being updated out
from under the connectors.
To fix these issues, this commit introduces a new lease acquired by
every instance of the connector, regardless of whether they read or
write, and gates migration on this lease. Since Every migration is gated
on this one lock, this has two effects:
1. We guarantee mutual exclusion for migrators.
2. No migration can happen if there's another connector attached to the
database.
This means that if a user wishes to update the connector version, …

Update lock handling for migrate

---

pkg/pgmodel/end_to_end_tests/main_test.go
pkg/pgmodel/end_to_end_tests/migrate_test.go
pkg/pgmodel/extension.go
pkg/pgmodel/migrate.go
pkg/pgmodel/upgrade_tests/upgrade_test.go
pkg/runner/runner.go
pkg/util/lock.go

This commit switches migration to use the same connection that holds the migration-lock instead of a separate connection pool. Using a separate pool has a failure mode where the connection holding the lock dies, but the pool remains alive and keeps migrating, potentially allowing a race among multiple migrators. If the same connection is used, the connection dying will also force migration to stop.

Ensure fate-sharing for the migration lock

---

cmd/promscale/main.go
pkg/api/common_test.go
pkg/api/health_test.go
pkg/api/labels_test.go
pkg/api/query_range_test.go
pkg/api/query_test.go
pkg/api/series_test.go
pkg/api/write_test.go
pkg/log/log.go
pkg/pgmodel/end_to_end_tests/main_test.go
pkg/pgmodel/upgrade_tests/upgrade_test.go
pkg/runner/runner.go
pkg/runner/runner_test.go
pkg/util/election_test.go
pkg/util/util_test.go

This commit adds a new log format flag which can be used for setting the format
of the logs to either logfmt (default) or json. It also cleans up logger flags
and initalization logic a bit.
Closes #261

Add log format flag and default to logfmt formatting for logs

---

pkg/log/log.go

We add a level of indirection before calling `Log()`, so we need an to report the location a level higher in the callstack than the default.

Fix log location reporting

---

docs/sql_schema.md

Adds the SQL code formatting to relevant blocks queries that were missing it and fixes the invalid syntax in the containment operator example.
Fixes #265

Update the docs/sql_schema.md containment operator example

---

pkg/internal/testhelpers/containers.go

ts_tune sets max_connections conservatively in newer TimescaleDB docker images.
This now breaks some of our tests on some environments due to running out of connections.
To avoid this, set max_connections explicitly back to the default.

Fix max_connections setting in tests

---

pkg/pgmodel/sql_ingest.go

Prevent a potential deadlock on the chunk's series_id, time unique
index.

Prevent potential deadlock

---

pkg/pgmodel/end_to_end_tests/promql_query_endpoint_test.go

This query had a logical error which was causing the tests to output lots
of logs, making the output noisy and hard to read.

Fix erroneous PromQL query in end-to-end tests

---

pkg/pgmodel/sql_ingest.go
pkg/pgmodel/sql_test.go

Previously, runInserterRoutine reported errors to two places:
1) the errChan originally starting the inserter
2) The errChan associated with the request it's handling
The reporting in (1) caused a send-on-closed-channel error
since the request that originally started the insert routine
is actually done after the first error and closes its errChan.
Another words, errors should always be reported on the errChan
assoicated with the request being handled, since we know that
request is still not done. As a plus, that's semantically more
correct too.
Thus, we get rid of (1) and keep (2). We also get rid of passing
errChan not associated with a request down -- this simplifies code
and prevents this type of error in the future.

Fix error reporting to prevent panic

---

docker-compose.yml

This simply makes the example docker-compose.yml clearer to read, normalize it a bit with common docker-compose usage, and avoid a pitfall with `db-ssl-mode` being the only option not set with env var

Make example docker-compose clearer

---

pkg/pgmodel/extension.go
pkg/pgmodel/migrate.go
pkg/version/version.go

Adds support for checking pg server version number on startup

---

pkg/pgmodel/sql_ingest.go

Otherwise future inserts will fail once the epoch is too old.

BUGFIX reset pendingBuffer epoch when we're done

---

helm-chart/templates/deployment-connector.yaml
helm-chart/values.yaml

This will give users more flexibility and enable them to pass HA configuration to promscale for example.
resolves timescale/promscale#307

Enable to pass arguments to the promscale container

---

cmd/promscale/main.go
pkg/api/common.go
pkg/api/router.go
pkg/runner/runner.go
pkg/runner/runner_test.go

Read-only mode is added to run against a read replica. In this mode, migration
and leader election is disabled. Write route will be missing and return 404
error code.

Add read-only mode to the connector

---

.github/workflows/gosec.yml
pkg/internal/testhelpers/containers.go

Note:
1. Most issues that this tool found are from `promql` which is excluded since we do not want to edit those changes. They seem mostly towards unhandled error returns which are from log.Warn, meaning, safe to ignore.

Add support for go-sec based vulnerability scanning

---

pkg/pgmodel/upgrade_tests/upgrade_test.go

Chunk numbers can change across runs of the upgrade tests causing spurious failures. This PR filters out those chunk numbers to make the tests more consistent.

Reduce noise in upgrade tests by filtering

---

pkg/pgmodel/upgrade_tests/upgrade_test.go
pkg/version/version.go

Instead of trying to determine the previous version for
the update tests, set it explicitly. Also set it as
far back as reasonable. Moving it back always adds
more code to what is tested, since more upgrade scripts
are run.

Specify the version to test upgrades from explicitly

---

docs/cli.md
pkg/api/common.go
pkg/api/common_test.go
pkg/api/router.go
pkg/api/router_test.go
pkg/runner/runner.go
pkg/runner/runner_test.go
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
pkg/tests/end_to_end_tests/router_test.go

This commit adds configuration flags for setting up HTTP Basic Authentication,
Bearer Token Authentication (JWT), and TLS certificate support for web server.

Add support for HTTP Basic Authentication and TLS for web endpoints

---

pkg/tests/end_to_end_tests/create_test.go
pkg/tests/end_to_end_tests/datasets_test.go
pkg/tests/end_to_end_tests/drop_test.go
pkg/tests/end_to_end_tests/promql_query_endpoint_test.go
pkg/tests/end_to_end_tests/promql_write_endpoint_test.go
pkg/tests/end_to_end_tests/query_integration_test.go
pkg/tests/end_to_end_tests/view_test.go

This change should improve our testing by making sure we are correctly
handling metric names with uppercase letters.
Closes #170

Add capitalized metric names to end-to-end tests

---

cmd/prom-migrator/README.md
pkg/migration-tool/planner/block.go
pkg/migration-tool/planner/planner.go
pkg/migration-tool/utils/client.go
pkg/migration-tool/writer/writer.go

This commit decouples the progress bars from writer and reader and
implements real-time speed updates on the fetching of block(s) side.

Provide real-time speed updates for fetching data in prom-migrator

---

pkg/internal/testhelpers/containers.go
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go

Prometheus can run background processes on its internal database to compact
the dataset, if a query is ran at this time, it is possible to get a 422
HTTP response. In this case, we just retry. This commit also adds some custom
Prometheus configuration to preserve the dataset intact.

Add retry on 422 HTTP status code from Prometheus in end-to-end tests

---

helm-chart/README.md
helm-chart/templates/config-maintenance.yaml
helm-chart/templates/cronjob-maintenance.yaml
helm-chart/templates/deployment-connector.yaml
helm-chart/values.yaml

The drop chunks job is now renamed to maintenance,
to reflect the name change of the underlying function
it called. 
Additionally the call is made more verbose to signify 
what was executed, and if it failed or succeeded. 
Fixes #299, with the solution provided in the issue
(thanks @franck102). And a replacement for #191 is added
with better nomenclature (due to inactivity on that PR) 
(thanks @halfmatthalfcat)

Update helm drop chunks job

---

pkg/pgmodel/extension.go

if there's nothing but zeroes in the version component it happens to strip
one too many for it should tolerate one leading zero if it also happens
to be a trailing one.

fix `trimLeadingZeros()`

---

pkg/api/metrics.go
pkg/api/metrics_test.go
pkg/runner/runner.go
pkg/runner/runner_test.go
pkg/tests/end_to_end_tests/migrate_test.go
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
pkg/util/util.go

Applied the `-tput-report` flag value to the write throughput calculator in
the exposed Prometheus metrics.
Fixes #367

Fix sample throughput report interval

---

pkg/version/version.go

Update the supported version range of promscale from `Safe: ">=1.7.3 <2.0.0"` to `Safe: ">=1.7.3 <2.1.0"`
Signed-off-by: Vineeth Pothulapati <vineethpothulapati@outlook.com>

Bump timescaleDB supported range to <2.1.0

---

README.md
docs/alerting-recording.md
docs/metric_deletion_retention.md

This PR contains docs for
1. Setting up alerting, recording rules at the Prometheus side. 
2. Metric deletion & metric retention using Promscale & TimescaleDB.

Add alerting & recording rules, series deletion & retention docs

---

pkg/internal/testhelpers/containers.go
pkg/pgmodel/common/extension/extension.go
pkg/pgmodel/migrate.go
pkg/runner/runner.go
pkg/runner/runner_test.go
pkg/tests/end_to_end_tests/main_test.go
pkg/tests/upgrade_tests/upgrade_test.go

**--install-extensions**: It installs the extenion if not present. By default set to true.  Formerly this flag was **install-timescaledb**
**--upgrade-extensions**: Upgrade extension to available next version. By default set to true.
**--upgrade-prerelease-extensions**: Upgrade to available highest prerelease if available. By default set to false.
1. Install TimescaleDB & Promscale extensions only if ``--install-extensions`` is enabled.
2. Upgrade TimescaleDB & Promscale to available latest version if ``--upgrade-extensions`` is enabled.
3. Upgrade TimescaleDB & Promscale to available latest `rc` version if --upgrade-prerelease-extensions`` is enabled.
Note:
1. If the current installed version in timescaleDB is an `rc` version we ignore `--upgrade-prerelease-extensions` flag that is set …

add flags for upgrade-extensions

---

.github/workflows/go.yml
pkg/tests/upgrade_tests/upgrade_test.go

Having two different test functions is creating flakiness in containers creation. So merging two different tests into one supporting test containers are spun up once on test invocation.

CI flaky issue fix

---

docs/cli.md
pkg/api/common.go
pkg/api/router.go
pkg/query/query_engine.go
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
pkg/tests/end_to_end_tests/query_integration_test.go

Fixes: #426
Fixes: #255
This commits adds support for configuring PromQL engine evaluation.
This widens our PromQL support in order to evaluate queries
that require some specific conditions.

Adds support for configuring PromQL engine evaluation via CLI flags.

---

pkg/api/write_test.go
pkg/ha/ha_parser.go
pkg/ha/ha_parser_test.go
pkg/ha/ha_service.go
pkg/ha/mock_ha_service.go
pkg/pgmodel/ingestor/ingestor_test.go

Instead of just returning a boolean accepting or denying
the insert from an instance, the HA service can now
accept an insert but specify a minimum accepted timestamp
so the parser can filter out samples outside of the lease
interval.

HA service returns minimum accepted timestamp

---

pkg/pgclient/metrics.go

Because these functions return the current number of cached items, they should be gauges not counters.   #437

Change cache size metrics to prom gauges

---

go.mod
go.sum
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
pkg/tests/end_to_end_tests/promql_label_endpoint_test.go
pkg/tests/end_to_end_tests/promql_query_endpoint_test.go
pkg/tests/end_to_end_tests/promql_series_endpoint_test.go
pkg/tests/end_to_end_tests/query_integration_test.go

Previously the PromQL tests on the real dataset didn't run because
the start and end variables in runPromQLQueryTests were incorrectly
shadowed.
Once that was fixed it was revealed that some of our queried didn't
match Prometheus - this was also a testing (and not real) issue. Turns
out our way of generating prom data was incorrect. Namely, to start up
prom correctly on the data the data should be snapshoted and not simply
left in plain DB mode.
Besides that we have some fixes to equality checking and the like.

Fix promQL integration tests

---

.github/workflows/go-scheduled.yml

Add timeout to go schedule job. As it's failing due to timeout  https://github.com/timescale/promscale/runs/1803289305?check_suite_focus=true
We added the timeout in `go.yml` and missed adding to `go-scheduled.yaml` for running the same tests.

Add timeout for tests in go-scheduled.yaml

---

pkg/api/router.go

While I was investigating promscale memory consumption I've found that heap profiling was missing, therefore let's add it and the rest of them.

Add pprof profiles

---

pkg/version/version.go

Support any 2.x version. By idea the 2.x line should not
break API and is safe to use.

Update accepted TS version

---

pkg/pgmodel/ingestor/buffer.go
pkg/pgmodel/ingestor/handler.go
pkg/pgmodel/ingestor/ingestor.go
pkg/pgmodel/ingestor/ingestor_sql_test.go
pkg/pgmodel/ingestor/insert.go
pkg/pgmodel/ingestor/inserter.go
pkg/pgmodel/model/interface.go
pkg/pgmodel/model/samples.go
pkg/pgmodel/model/sql_test_utils.go

Previously samples were stored in the SampleInfoIterator
as an slice of structs. Change this to be a slice of interfaces
and have the interface be fulfilled by a pointer instead of a struct.
This improves memory usage and introduces a cleaner api through use
of an interface. This interface will also be useful if we start
supporting samples other than prometheus.

Optimize memory usage: samples

---

pkg/runner/client_test.go
pkg/runner/flags.go
pkg/runner/flags_test.go
pkg/util/util.go
pkg/util/util_test.go

In the case where you set an environment variable with the wrong type
(for example, set a string where an int flag is defined), parsing errors
were ignored. This commit adds proper error handling for that case.

Add error handling to env variable parsing

---

helm-chart/README.md
helm-chart/templates/deployment-connector.yaml
helm-chart/values.yaml

Update Promscale deployment upgrade strategy to Recreate as we expect no Promscale pod to be connected to TimescaleDB during the upgrade.

Fix Promscale deployment upgrade from Rollingupgrade to Recreate strategy

---

docs/cli.md
pkg/pgclient/client.go
pkg/pgclient/config.go
pkg/pgclient/metrics.go
pkg/pgmodel/ingestor/ingestor.go
pkg/pgmodel/ingestor/inserter.go

By default pgx uses prepared statements implicitly.
But this makes it incompatible with PGBouncer. 
The statements used are cached in each pgx connection
separately, and the size of the statement cache is
configurable. This statement cache helps with query 
performance, disabling it (by preferring the simple
protocol) reduces performance by more than 20%. But 
not having a large enough statement cache can hurt 
performance by up to 50%. 
This PR adds an option for the user to select whether they
want to disable the statement cache by setting the 
`--db-statements-cache` flag to false. The PR also makes 
the statement cache depend on the size of the configured
metrics cache, as the expected number of metrics is a good
estimator for the required statements to be cached.

Make db driver statement cache be configurable

---

docs/cli.md
pkg/api/common.go
pkg/api/query.go
pkg/internal/testhelpers/containers.go
pkg/query/query_engine.go
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
pkg/tests/end_to_end_tests/promql_label_endpoint_test.go
pkg/tests/end_to_end_tests/promql_query_endpoint_test.go
pkg/tests/end_to_end_tests/promql_series_endpoint_test.go

This does 3 tasks:
1. Fix PromQL E2E tests that were showing error logs.
2. Make CI fail if PromQL tests actually fail in logs (other than places not intended, eg: real-dataset tests where we want the output to be in line with Prometheus).
3. Support `promql-negative-offset` as the list of enable-features.

Fix failing PromQL tests, fail on error logs and support for negative-offset in enable-features.

---

helm-chart/README.md
helm-chart/templates/config-maintenance.yaml
helm-chart/templates/cronjob-maintenance.yaml
helm-chart/templates/deployment-connector.yaml
helm-chart/values.yaml

Disable maintenance cronjob by default as we expect all users to use >= TimescaleDB `2.0` and Also added an option to configure podAffinity & podAntiAffinity rules for Promscale deployment & Maintenance cronjob.

Update Promscale helmchart

---

pkg/pgmodel/model/interface.go
pkg/tests/end_to_end_tests/db_connections_test.go

This test verifies that the system can detect when the connection
to the DB cannot be established. It also checks that operation resumes
as normal as soon as the connection can be established again.

Add DB connection handling end-to-end test

---

pkg/ha/ha_service.go
pkg/tests/end_to_end_tests/ha_single_promscale_test.go

The check for last write interval was checking integer variable which
should have been in seconds but compared to nanoseconds. This fix updates
that variable to contain time in seconds.

Fix HA bug with last write interval

---

pkg/tests/testdata/expected/info_view-timescaledb-2-multinode.out
pkg/tests/testdata/expected/info_view-timescaledb-2.out

With the TSDB version 2.2.0, `hypertable_detailed_size` has been updated to
include overhead size. This change updates the golden test file to account
for this change.
More details can be found here:
https://github.com/timescale/timescaledb/pull/2989

Fix golden file end-to-end test for latest TSDB version

---

pkg/tests/end_to_end_tests/delete_test.go
pkg/tests/end_to_end_tests/zlast_test.go

Some tests were not running metric creation finalization after ingesting
a pretty big dataset which caused test failures from time to time. This commit
adds the missing calls to make tests less flaky.

Fix delete end-to-end tests

---

.github/workflows/go.yml
pkg/tests/end_to_end_tests/golden_files_test.go

Log output from our test runs can be too verbose and slows down development
work when searching through them. This change stores complete logs into individual
files and stores them as GA artifacts while also filtering out the output to the
essential failure messages.

Store test logs as GA artifacts

---

pkg/pgmodel/querier/querier_sql_test.go
pkg/pgmodel/querier/query_builder.go
pkg/tests/end_to_end_tests/promql_query_endpoint_test.go

Previously, regex anchoring happened as ^str$, which broke when using
a pipe as it interpreted a|b as (^a)|(b$).  while what we want is
^(a|b)$. Anoher words the precedenc of operators broke. Now we found
the anchoring Prometheus does, and just used that.

Fix regex anchor

---

go.mod
go.sum
pkg/migration-tool/integration_tests/integration_test.go
pkg/migration-tool/integration_tests/remote_writer_test.go
pkg/migration-tool/planner/slab.go
pkg/migration-tool/utils/client.go

Solves gaps created during the migration process, when using concurrent fetch. The issue was that while we fetch a slab concurrently (dividing into sub-slabs in terms of time-ranges and pulling them concurrently), we need to combine them into a single large time-series before pushing to the writer. However, the combination process did not care about the time order i.e., the order in which concurrent sub-slabs were fetched and combined randomly. This is now fixed and we combine only in the order of creating sub-slabs.

Prom-migrator: Fix gaps in graphs when migrating on time-based storages.

---

docker-compose/docker-compose.yaml
docker-compose/high-availability/docker-compose.yaml
docs/docker.md

Remove `build: context: .` to drop dependency to build Promscale image on setting up Promscale. i.e. removed from Promscale service.
```
build:
context: .
```
Noticed Error:
```
$ docker-compose up
Building promscale
[+] Building 0.0s (1/2)                                                                                  
=> [internal] load build definition from Dockerfile                                                0.0s
=> => transferring dockerfile: 2B                                                                  0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount685150454/Dockerfile: no such file or directory
ERROR: Service 'promscale' failed to build
```
**Note**: This error is observed only when …

Add new docker-compose file to use without build dependency

---

pkg/util/util.go
pkg/util/util_test.go

Previous implementation did not cover all possible cases that needed.
This change also reduces the number of regexes necessary to mask all
combinations.
Fixes #605

Improve password masking utility

---

.github/workflows/go-scheduled.yml
.github/workflows/go.yml
Makefile
docs/cli.md
pkg/api/common.go
pkg/api/query_range.go
pkg/api/query_range_test.go
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
pkg/tests/upgrade_tests/upgrade_test.go
pkg/util/util.go
pkg/util/util_test.go

Signed-off-by: Harkishen Singh <harkishensingh@hotmail.com>
Fixes: #608 
If we make `max-samples` configurable as per user, then `max-points` should be made configurable as well, with the default being what Prometheus has. Moreover, being fixed at 11,000 based on estimation is smart, but may not be necessary to all systems.

Make per timeseries points limit configurable.

---

docs/docker.md

Wrapped the maintenance example in `docker exec`.
Provides the information I did mis:
* How? (`docker exec`)
* Which container? (`timescaledb`)
* Which user inside the container? (`postgres`)
* Which program in the container? (`psql`)

Maintenance also inside docker container

---

pkg/api/read.go
pkg/api/read_test.go
pkg/api/router.go
pkg/ha/filter.go
pkg/log/log.go

In the new HA setup read path fails when the read query comes from prometheus as promethues appends replica labelset from external labelset for readRead requests. So dropping the __replica__ labelSet in labelmatchers for read requests, when Promscale is in HA mode.

Fix new HA read path by dropping __replica__ labelset

---

pkg/internal/testhelpers/containers.go
pkg/pgmodel/ingestor/copier.go
pkg/tests/end_to_end_tests/golden_files_test.go
pkg/tests/testdata/expected/info_view-timescaledb-2-multinode.out

The biggest change was to fix which error message triggers
decompression. That's the only functional change.
The rest are changes in the golden files to show that the
compression status has been fixed.

Fixes to support timescale 2.3.0

---

go.mod
go.sum
pkg/pgclient/client.go
pkg/pgclient/config.go
pkg/pgclient/config_test.go
pkg/runner/client.go
pkg/runner/runner.go
pkg/util/util.go
pkg/util/util_test.go

We have had some issues while trying to correctly mask logged
passwords supplied by the user. This change removes the utility
function used to mask them and using more reliable ways to redact
sensitive connection data. Since `pgconn` is now redacting password
data itself when trying to parse connection strings, we don't need
to manually mask the output errors ourselves.
Fixes #645, #641

 Use more reliable methods of password masking

---

pkg/pgmodel/ingestor/ingestor_sql_test.go
pkg/pgmodel/ingestor/metric_batcher.go
pkg/pgmodel/ingestor/metric_batcher_test.go
pkg/pgmodel/model/interface.go
pkg/tests/end_to_end_tests/concurrent_sql_test.go

Previously, bad error checking logic in MetricTableName could
have returned a blank table name on error which eventually
led to the following postgres error:
"ERROR: zero-length delimited identifier at or near \"\"\"\" (SQLSTATE 42601)"
As reported in issue #668
This fixes that and adds defensive checks to avoid blank table name.
It's not clear what the underlying error was though.

Fix bad check for error in MetricTableName

---

pkg/promql/engine.go
pkg/tests/end_to_end_tests/promql_query_endpoint_test.go

This is especially important for comparitive queries like:
sum(rate(requests{error="true"})) / sum(rate(requests))

Allow pushdown of multiple clauses in a single query

---

.github/workflows/go-scheduled.yml
.github/workflows/go.yml
pkg/internal/testhelpers/containers.go
pkg/tests/end_to_end_tests/main_test.go
pkg/tests/upgrade_tests/upgrade_test.go

Signed-off-by: Harkishen Singh <harkishensingh@hotmail.com>
This PR adds support for smoke testing Promscale against nighty builds of TimescaleDB, both in regular and multi-node modes.

Adds support for TimescaleDB nighty smoke tests.

---

pkg/pgmodel/querier/query_builder.go
pkg/version/version.go

This is the newest version of the extension.
Start support for pushdowns of vector selector
and rate/increase with this version as the
beta had some correctness issues with rate/increase.

Add support for promscale ext 0.2.x

---

.github/workflows/go-scheduled.yml
.github/workflows/go.yml

Promscale extension was a part of the Promscale repo in the past, that
is the reason why we were running extension building in our CI process.
Removing will speed up the Promscale CI process considerably and the
extension building will be moved to extension repo.

Remove promscale extension building from CI process

---

pkg/runner/client.go

Move warning log to debug log, as it confuses the users. On Promscale start-up users see the warning log by default stating the older HA system is disabled. 
`
level=warn ts=2021-07-28T17:31:24.279Z caller=client.go:154 msg="No adapter leader election. Group lock id is not set. Possible duplicate write load if running multiple connectors"
`

Change warning log to debug log 

---

pkg/pgclient/config.go
pkg/pgmodel/ingestor/copier.go
pkg/pgmodel/ingestor/dispatcher.go
pkg/pgmodel/ingestor/handler_test.go
pkg/pgmodel/ingestor/ingestor_sql_test.go
pkg/pgmodel/ingestor/metric_batcher.go
pkg/pgmodel/ingestor/series_writer.go
pkg/pgmodel/model/sql_test_utils.go

Previously, series creation was done by the metric batcher.
But there was some performance issues with that:
1) There are lots of metric batchers and thus potentially
lots of db calls to create series. This did cause the series
creation to be blocked on waiting for a db connection
from the pool
2) In general, less batching of series creation calls to the DB
To solve this, we move series creation to the copier and factor it out
into a SeriesWriter class. In addition we had to add logic to handle series
creation across metrics.

Move series creation to copier

---

helm-chart/templates/cronjob-maintenance.yaml

change `promscal` -> `promscale` on line 60
```
Error: UPGRADE FAILED: template: promscale/templates/cronjob-maintenance.yaml:60:25: executing "promscale/templates/cronjob-maintenance.yaml" at <include "promscal.fullname" .>: error calling include: template: no template "promscal.fullname" associated with template "gotpl"
```

helm chart - typo in cronjob template

---

pkg/pgmodel/ingestor/copier.go
pkg/tests/end_to_end_tests/db_connections_test.go

Previously, the copier quit if WriteSeries or orderExemplarLabelValues failed.
This is wrong since errors can be transient and copiers aren't restarted.
Instead, errors should be reported but copiers shouldn't exit.
This PR fixes the logic as well as a test that should have but didn't detect this.

Fix copier error handling

---

.github/CODEOWNERS
CODEOWNERS

Move CODEOWNERS to the .github dir since it only applies to GitHub and we want the root dir clean.
Additionally, add more config lines to CODEOWNERS for SQL related portions of the code.

Move CODEOWNERS to .github

---

.github/workflows/go.yml
pkg/internal/testhelpers/postgres_container.go
pkg/tests/end_to_end_tests/continuous_agg_test.go
pkg/tests/end_to_end_tests/main_test.go
pkg/tests/upgrade_tests/upgrade_test.go
pkg/version/version.go

This commit mostly just adds test for PostgreSQL 14.
Since the Promscale extension doesn't yet support PG14,
tests with the extension cannot use PG14. This should
be changed as soon as the extension adds support (should
be soon now). TODOs have been added for this.
Also, when all the kinks for testing with PG14 are ironed out,
our default tests should be changed to PG14, both with CLI flags
and with our CI.

Add support for PG14

---

helm-chart/README.md
helm-chart/templates/deployment-promscale.yaml
helm-chart/templates/secret-connection.yaml
helm-chart/templates/service-account.yaml
helm-chart/templates/service-monitor.yaml
helm-chart/values.yaml

Few improvements:
- include creation of ServiceAccount
- allow creation of ServiceMonitor (especially useful for tobs)
- move all connection details into a Secret object and read them with `envFrom`
- allow overriding Secret object and thus provide a hidden way to inject arbitrary environment variables
- use sha256 checksum as pod annotation to force pod recreation when connection values change
breaking changes:
- `connection.password` is no longer a map and now only accepts a string with password value
- `connection.uri` is no longer a map and now only accepts a string with uri value
Sorry for one large PR and not multiple smaller ones. I didn't want to deal with merge conflicts. Different features are implemented in different commits though.

Helm improvements

---

pkg/tests/end_to_end_tests/tag_op_test.go

There are 15 operators defined in the ps_tag schema. Each
can deal with at least one and in many cases many input types.
Test that the operators return the correct composite types
and that the fields contain the correct values.
These tests do not modify the contents of the database.

Add tests to validate the tag operators

---

pkg/runner/flags.go
pkg/runner/flags_test.go

The TS_PROM_ prefix was deprecated in Promscale release 0.1.4, released
in December 2020.

Remove deprecated TS_PROM_ prefixed env-var support

---

docs/cli.md
pkg/pgclient/config.go
pkg/pgclient/config_test.go

As far as I can tell, this parameter was never used. It was introduced in https://github.com/timescale/promscale/commit/e56974b961180ce33ad8daaba47d5de2df13b4f2, and apparently never used there either.
Perhaps the original intention was that it would flow into the `maxRetries` parameter of [getConn](https://github.com/timescale/promscale/commit/e56974b961180ce33ad8daaba47d5de2df13b4f2#diff-553897b3aa8771440b16199f81fac786b88d9a8bdbe15c95815bfaed2a4c9ed9R51).

Remove unused `db-connect-retries` cli flag

---

helm-chart/templates/secret-connection.yaml

This prevents failure in the unlikely event of passing some connection parameters as numbers.
cc @VineethReddy02 @JamesGuthrie

helm-chart: allow numbers to be passed as connection parameters

---

cmd/prom-migrator/main.go
cmd/prom-migrator/main_test.go

Testing that depends on current time is usually flaky. This change wraps
`time.Now().Unix()` calls into an independent function which can be
manipulated to always return the same value thus making test more reliable.

Make prom-migrator unit test independent of current time

---

pkg/api/label_values.go
pkg/api/labels.go
pkg/api/series.go
pkg/promql/engine.go
pkg/promql/engine_test.go
pkg/promql/test.go
pkg/query/queryable.go
pkg/thanos/store.go

Fixes memory leak by adding Close() calls to SampleQuerier instances
This matters whenever Select is called as in those cases the Close
trickles down to sampleRow.Close() calls which returns memory to pools.
Fixes timescale#933.

Fix memory leak with SamplesQuerier

---

helm-chart/README.md
helm-chart/templates/deployment-promscale.yaml
helm-chart/templates/svc-promscale.yaml
helm-chart/values.yaml

Solves #918
PR is based on top of #924 as changes from that PR as essential here.
Breaking changes:
- `args` section is moved to `extraArgs` to note that arguments may be added using other parameters
- `tracing` section moved to `openTelemetry`
Enhancements:
- enabling OT tracing can be done just with `openTelemetry.enable` parameter and do not require setting any other parameters
- tracing port name changed to reflect its relation to OpenTelemetry

helm: Simplifying enablement of otel tracing

---

build/Dockerfile

Reorganized the order of certain Dockerfile commands so we can speed up
image builds. This enables Docker to re-use cached layers if files haven't changed.
This mainly addresses slowness of `go mod download`.
Another optimization we can do is reusing build caches but that requires bigger changes so I'll leave that for another PR.
With new Dockefile my local build time improved from 200s -> 70s ;)

Speed up Docker builds with caching

---

.gitignore
Makefile

The `./pkg/tests/end_to_end_tests/ingest_trace_test.go` tests require
a dataset file. This file is fairly large, and is stored out-of-band
in a second GitHub repo. This commit adds a make target to make it
easy for folks to download this file into the correct place in the
code tree.

Add Make Target for Downloading Trace Dataset

---

.github/workflows/go.yml
pkg/internal/testhelpers/postgres_container.go
pkg/tests/end_to_end_tests/continuous_agg_test.go
pkg/tests/end_to_end_tests/main_test.go

We run the full test suite against the most recent postgres version, and
a subset against older versions. This change promotes our full test
suite to test against PG14.

Run full test suite on PG14

---

pkg/pgmodel/common/extension/extension.go

Back in 3af97e9f we introduced a variable for the Timescale extension's
schema, but it was not used in the extension migration.

Use timescale extension schema variable in migration

---

docs/cli.md
pkg/pgclient/config.go

Based on benchmarks having it set to 1 performs much better so let's have it as a default.
Also rewording a description for the given flag to make it more clear what it does.

Change the default for `db-writer-connection-concurrency`

---

pkg/api/metrics.go
pkg/runner/runner.go
pkg/telemetry/promql.go
pkg/telemetry/telemetry.go
pkg/tests/end_to_end_tests/migrate_test.go
pkg/tests/end_to_end_tests/telemetry_test.go

Telemetry collection also involves calculating quantiles that need the help
of PromQL expression. This commit implements the same. As of now, we
calculate p50, p90, p95, p99 of response durations of /query.* endpoints
and the /fetch_traces API (via GRPC).

Adds support for PromQL based telemetry stats.

---

docs/cli.md
docs/dataset.md
pkg/dataset/config.go
pkg/dataset/config_test.go
pkg/runner/client.go
pkg/runner/flags.go
pkg/tests/end_to_end_tests/config_dataset_test.go

Configuring chunk interval at startup enables users to fine tune their
metrics dataset using only Promscale.
Fixes #974

Add ability to configure chunk interval on startup

---

pkg/pgmodel/ingestor/copier.go
pkg/pgmodel/ingestor/metric_batcher.go
pkg/pgmodel/ingestor/metric_batcher_test.go
pkg/pgmodel/model/batch.go

If Prometheus retries sending samples  Promscale can attempt to insert duplicate data.
This can result in a row deadlock. Deadlock is detectable by PG when running on a singlenode.
However in a multinode setup that does not work due to distributed nature.
We make sure to always sort series before inserting to avoid the deadlock.
We don't sort samples in the series because they should already be sorted by Prometheus.
Closes https://github.com/timescale/promscale/issues/975

Prevent row deadlock

---

docs/docker.md

Add clarification that the cron job to run execute_maintenance is only needed with TimescaleDB 1.X

Cron job only needed for TSDB 1.X

---

docs/tracing.md

A user in our community Slack reported that the instructions don't work because we added the -enable-feature flag but we kept the 0.7..0-beta.latest tag in the docker run command for the Promscale connector

Pull latest promscale image

---

pkg/pgclient/client.go
pkg/pgclient/config.go
pkg/pgclient/config_test.go
pkg/pgmodel/ingestor/ingestor.go
pkg/runner/flags.go

There were two problems with async flag. First it was present
in two Config structs and parsed in the struct that is not being
used. Second was that async flag was not passed when creating
sub-config structure. This resulted in async flag not being
applied.
Also removing some unused config.
Hopefully in future we will increase test coverage for flags and configs so we catch this easily. 
It seems we would need a decent amount of refactoring to support these tests so I'll leave it for another PR.

Fix passing of async flag

---

pkg/runner/flags.go
pkg/runner/flags_test.go

This is a deprecated flag but we still need it for compatibility reasons.

Add `db-writer-connection-concurrency` flag back

---

deploy/helm-chart/Chart.yaml
deploy/helm-chart/templates/svc-promscale.yaml

Hello,
While playing around with the Helm chart, I saw an issue when using a custom `prometheus.port` or `openTelemetry.port` value. Currently, the service will automatically use the custom configuration as the `targetPort`, which will fail as those ports are not customizable.
The fix proposes to hardcode the  `targetPort` bindings to the Deployment's named ports.
Let me know if you have any remarks about it. :)

fix(helm): use fixed target port on svc-promscale

---

Makefile
build/Dockerfile

Since we statically implement content of SQL files into Go code we need to run `go generate` to make
sure we use the latest SQL code.

Run `go generate` in Makefile and Dockerfile

---

docs/metric_deletion_and_retention.md

Added SQL a command to the docs for getting the default metric retention period. This is useful for idempotency checks in config management tools like Puppet, Ansible, etc.

Added SQL command to get current default retention period

---

ct.yaml
deploy/helm-chart/Chart.yaml
deploy/helm-chart/templates/deployment-promscale.yaml
deploy/helm-chart/templates/secret-connection.yaml
deploy/helm-chart/templates/service-account.yaml
deploy/helm-chart/templates/service-monitor.yaml
deploy/helm-chart/templates/svc-promscale.yaml

I need statically defined labels to easily create pod anti affinity rule before deploying promscale ([this doesn't work](https://github.com/timescale/savannah-infra/pull/1168/files#diff-86f3fceb69e1bd3fda16d679c62b89b749dcf97360925716e339e597bf87707fR33-R36)). To do this we can pre-define few of [kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). I have defined only 3, but in the future we can add more.

deploy/helm-chart: add kubernetes recommended labels

---

.github/workflows/helm.yml

This job compiles and publishes the helm release. It works
by downloading the latest index, and then packaging the new
chart and adding it to the new index, and uploading it back
to the S3 bucket.
There is a possible race condition that if two such jobs
execute at the same time only one of the jobs will have it's
chart added to the repo. This is not very likely though.
The other alternative is to have a git repo for all the charts
and upload from there. This avoids the possibility of a race
condition but is a more complex solution.

Add the helm release CICD job

---

docs/cli.md

The `migrate` option is deprecated.

Remove deprecated `migrate` from CLI.md

---

docker-compose/prometheus.yml

This adds Promscale as a scrape target to the prometheus config we provide with our docker-compose. It should give visibility to the fact that Promscale can be scraped by prometheus.
- [-] CHANGELOG entry for user-facing changes
- [-] Updated the relevant documentation

Add Promscale as scrape target in docker-compose config

---

docs/binary.md

The instructions don't tell people how to specify a host and port if TSDB is not running locally on the default port. I've just added the two parameters to the promscale command.

Add database host and port to instructions

---

.github/workflows/helm.yml
CHANGELOG.md
deploy/helm-chart/templates/secret-connection.yaml
deploy/helm-chart/values.yaml

This allows simplifying configuration for cases when DB is in the same namespace as promscale-connector. To illustrate:
```shell
$ helm template --namespace ns . | grep PROMSCALE_DB_HOST
PROMSCALE_DB_HOST: "timescaledb.ns.svc.cluster.local"
```
I also changed the default db name to `tsdb` as this is also the default name when using timescaledb on cloud.

deploy/helm-chart: allow templating connection values

---

CHANGELOG.md
go.mod
go.sum
pkg/runner/runner.go

Fixes: #1060 
This commit instruments grpc server in Promscale with Prometheus's
go-grpc-prometheus lib. This adds metrics for Promscale's grpc server.
Reference: https://github.com/grpc-ecosystem/go-grpc-prometheus

Adds prometheus instrumentation for grpc server.

---

.github/workflows/helm.yml

Add the --relative flag. This makes the url set in the index.yaml
use relative urls instead of s3://chart.timescale.com/* which doesn't
work since the charts are accessed using https.

Make helm publish use relative URLs

---

docs/high-availability/prometheus-HA.md
pkg/runner/flags.go

Old CLI flag for high availability was referenced in one of the docs and that old flag did not have the necessary alias.
This change fixes that.
Fixes #1073 

Update HA doc and add old HA CLI alias

---

CHANGELOG.md
build/Dockerfile
pkg/telemetry/metadata.go

This commits fixes the `promscale_packager` telemetry field that was
earlier showing `unknown` for all docker deployments. Now, it will show
`promscale_packager: docker` in the `_timescaledb_catalog.metadata`
table.
Metadata table output
```shell
promscale_packager                                          | docker                               | t
promscale_os_node_name                                      | 2bce24e46fcc                         | t
```
Please take into account the following non-code changes that you may need to …

Fix broken `promscale_packager` telemetry field for docker envs.

---

pkg/pgmodel/querier/common.go
pkg/pgmodel/querier/querier_sql_test.go
pkg/pgmodel/querier/query_tools.go
scripts/end_to_end_tests.sh

With the recent optimization, we have added metric IDs to metric cache
but when running queries on metrics that exist before the ingestion path
generates the cache, cache will be created with invalid metric ID values.
This change fixes that and adds end-to-end test for verifying that
cache is properly generated when this situation occurs.

Fix metric info cache loading when using query path

---

CHANGELOG.md
docker-compose/docker-compose.yaml
docker-compose/otel-collector-config.yml

This change adds a tracing configuration to our docker-compose, leveraging Promscale's trace output.

Add a simple tracing setup to the docker-compose

---

CHANGELOG.md
pkg/pgmodel/ingestor/trace/writer.go
pkg/tests/end_to_end_tests/dataset_traces_test.go

I have seen instances in which promscale attempts to insert spans that have an end time < start time. There is a database check constraint that catches this error, but it results in dropped spans. This patch catches the issue in Go and swaps the start and end times so that the spans will be inserted successfully.
[Issue](https://github.com/timescale/promscale/issues/1092)

Ensure that span start <= end

---

CHANGELOG.md
pkg/pgmodel/querier/query_builder_samples.go
pkg/tests/end_to_end_tests/promql_query_endpoint_test.go

Under certain circumstances, pushdown queries using promscale-extension
aggregates fail.
The failure comes from the fact that the start and end parameters passed
to the aggregate don't correctly align with the actual data which is
aggregated over by the query.
A call to the prom_rate aggregate looks something like the following:
```sql
SELECT
prom_rate(start, end, step_size, range, sample_time, sample_value)
FROM a_metric
WHERE a_metric.t >= data_start
AND a_metric.t <= data_end
```
If the time span [data_start, data_end] delivers results which are
outside of the time span [start, end], the aggregate function errors.
In general, this bug appeared when an aggregate pushdown function (such
as PromQL rate) is used together with a vector selector, such that the
lookback of the vector selector …

Fix broken pushdown queries

---

.github/workflows/docker-compose-tests.yml
.github/workflows/go-releaser.yml
.github/workflows/go-report-card.yml
.github/workflows/go-scheduled.yml
.github/workflows/go.yml
.github/workflows/gosec.yml
.github/workflows/integration.yml
pkg/tests/end_to_end_tests/telemetry_test.go
pkg/tests/end_to_end_tests/trace_delete_test.go

GitHub's documentation on `run` [1] and `shell` [2] implies that
commands invoked via bash will be run with `pipefail`. Unfortunately
this is not the case. Specifying `bash` as the `shell` does activate
`pipefail`, and prevent errors in test execution from being swallowed.
[1]: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun
[2]: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsshell

Prevent swallowed build errors in e2e tests

---

pkg/pgmodel/common/extension/extension.go

Prevent success log message from showing up if TS extension update failed.
Note that Promscale can continue to operate since we are still within the valid version range. However we can make this more strict if needed.

Don't log success message if extension update failed

---

pkg/api/query_test.go
pkg/pgclient/client.go
pkg/pgclient/client_test.go
pkg/pgmodel/querier/interface.go
pkg/pgmodel/querier/querier.go
pkg/pgmodel/querier/querier_sql_test.go
pkg/pgmodel/querier/query_exemplar.go
pkg/pgmodel/querier/query_remote_read.go
pkg/pgmodel/querier/query_sample.go
pkg/tests/end_to_end_tests/multi_tenancy_test.go
pkg/tests/end_to_end_tests/nan_test.go
pkg/tests/end_to_end_tests/null_chars_test.go
pkg/tests/end_to_end_tests/query_integration_test.go

The Querier interface was a weird mixture of "method to query" and
"methods to get things with which to query". This change moves "method
to query" into its own interface.

Refactor out RemoteReadQuerier interface

---

cmd/promscale/main.go
pkg/api/common.go
pkg/log/log.go
pkg/runner/flags.go
pkg/runner/flags_test.go
pkg/util/util.go
pkg/util/util_test.go

This PR contains a couple of changes that are connected to the renaming process of old flags. Main feature is the addition of logging usage of deprecated flags with recommendations on how to migrate them.
I'm unsure if any of this should be added to the changelog, perhaps only the change to remove the deprecated flags in 0.11.0 version. I would like some input on that before adding it.

Log deprecated flag usage

---

pkg/api/write.go
pkg/api/write_test.go
pkg/pgmodel/ingestor/trace/batch.go
pkg/pgmodel/ingestor/trace/writer.go
pkg/pgmodel/metrics/ingest.go
pkg/pgmodel/model/sql_test_utils.go
pkg/pgxconn/pgx_conn.go

Add few more metrics that will give us more insight into ingest.
Mainly we want to see how big our insert batches are and also the time it
takes to insert various trace related objects. This should help
us in finding weak spots.

Increase visibility into trace ingest

---

.github/workflows/go-releaser.yml
.goreleaser.yaml
.goreleaser.yml

Cannonical location for goreleaser config file is in root of the repository. In https://github.com/timescale/promscale/pull/1133 we merged a config in this location but it was not picked up during release as we already had another, "hidden" config in `build/` directory. To limit future confusion this PR is moving configuration to the TLD.

move goreleaser config to common location

---

.github/dependabot.yml
.github/workflows/go.yml

Some of the dependencies release new versions very quickly leading to
a lot of PRs generated by dependabot. Reducing the frequency to weekly
makes it more manageable to maintain the dependencies.

Reduce dependabot frequency to update Go deps weekly

---

go.mod
go.sum

There has been a bug in a way PGX reacted to context timeouts
https://github.com/jackc/pgx/issues/1156 .
We probably want to upgrade to next PGX release once it's out.
Closes https://github.com/timescale/promscale/issues/1176

Upgrade PGX to latest master

---

pkg/api/metrics.go
pkg/api/router.go
pkg/api/write.go
pkg/api/write_test.go
pkg/pgmodel/ingestor/copier.go
pkg/pgmodel/ingestor/trace/writer.go
pkg/pgmodel/metrics/ingest.go
pkg/tests/end_to_end_tests/ha_single_promscale_test.go

This PR fixes ingested_samples telemetry by using another metric name for items (aka insertables) received.
TODO:

Fix ingested_samples_total telemetry

---

CHANGELOG.md
pkg/api/read.go

Previously, we were trying to update the header but that cannot be
done in this instance since we are already starting to write the
request body. Only valid way of handling these situations is to
log the error and finish the request.

Log warning when remote read request is cancelled midway

---

CHANGELOG.md
README.md
docs/mixin/README.md
docs/mixin/alerts/alerts.yaml

This PR adds alerting rules for Promscale based on the metrics that are already exposed.
Note: The `for` field is written assuming `30s` scrape interval for most systems.

Add alerting rules for Promscale.

---

pkg/pgmodel/querier/clauses.go
pkg/pgmodel/querier/common.go
pkg/pgmodel/querier/query_builder.go
pkg/pgmodel/querier/query_builder_samples.go
pkg/promql/engine.go

The StartTime and EndTime values stored in QueryHints were superfluous,
and can be derived from other time ranges which are already available.

Remove StartTime and EndTime from QueryHints

---

.github/renovate.json

Prometheus library versions need to be pinned by us in order to work
properly with Promscale.

Make Renovate bot ignore pinned Prometheus version

---

.github/env
.github/renovate.json
.github/workflows/go-releaser.yml
.github/workflows/go-scheduled.yml
.github/workflows/go.yml
.github/workflows/helm.yml
.github/workflows/integration.yml
.github/workflows/mixin.yml

This is allowing renovate to handle tooling versions used in github actions. Configuration was tested in tobs repository after https://github.com/timescale/tobs/pull/268 and https://github.com/timescale/tobs/pull/274 were merged. 
https://github.com/timescale/tobs/pull/268 contains more of the reasoning behind this change.
This PR is finalizing a CI overhaul started in October by moving management of all dependencies to renovatebot.

.github: control tooling version used in CI via renovate

---

pkg/pgmodel/ingestor/trace/writer.go
pkg/pgmodel/model/sql_test_utils.go
pkg/pgxconn/pgx_conn.go

Using Postgres COPY FROM resulted in 2X improvements for trace ingest performance.
Here we use COPY FROM for inserting spans, links and events into respective hypertables.
COPY FROM uses binary protocol so it's expected to perform well.

Ingest traces using COPY FROM

---

.github/renovate.json

The gomod manager never puts the name of the module being updated in the
title, so putting the version in the title is just confusing.

renovate: Do not show version of dependency being update for gomod

---

CHANGELOG.md
docs/configuration.md
pkg/api/common.go
pkg/runner/flags.go
pkg/runner/flags_test.go
pkg/runner/runner.go
scripts/end_to_end_tests.sh

We are moving tracing support out of optional to on by default. This means
removing the --enable-feature option for tracing and logging a warning
if somebody is still using it unnecessarily. OTLP GRPC server will
always be started by default on port 9202.

Enable tracing flags by default

---

CHANGELOG.md
go.mod
pkg/runner/runner.go

Fixes: #1182 
This PR improves the logging of Promscale on the start. 
The logs now will be
```shell
level=warn ts=2022-03-03T07:54:25.175Z caller=extension.go:59 msg="could not install promscale: the extension is not available. continuing without extension"
level=info ts=2022-03-03T07:54:25.186Z caller=client.go:146 msg="Prometheus HA is not enabled"
level=info ts=2022-03-03T07:54:25.192Z caller=client.go:116 msg="postgresql://postgres:%2A%2A%2A%2A@localhost:5432/timescale?application_name=promscale%400.11.0-dev.0&connect_timeout=60&sslmode=allow" numCopiers=8 pool_max_conns=80 pool_min_conns=8 statement_cache="512 statements"
level=warn ts=2022-03-03T07:54:25.215Z caller=telemetry.go:56 msg="Promscale collects anonymous usage …
```

Improve logging of active servers on start.

---

.goreleaser.yml
Makefile
build/Dockerfile
cmd/promscale/main.go
pkg/runner/runner.go
pkg/version/version.go

We expose version, commit and branch. This information is useful for
comparing benchmark numbers across various builds.

Expose build information through Prometheus metrics

---

pkg/telemetry/telemetry.go
pkg/tests/end_to_end_tests/telemetry_test.go

Fixes: https://github.com/timescale/o11y-team-applications/issues/145
Same as the heading.

Verify telemetry engine as `nil` if TimescaleDB is not installed.

---

pkg/api/router.go
pkg/jaeger/api.go
pkg/jaeger/query/metrics.go
pkg/jaeger/query/query.go
pkg/pgclient/client.go
pkg/pgmodel/ingestor/ingestor.go
pkg/pgmodel/ingestor/trace/writer.go
pkg/runner/runner.go
pkg/telemetry/telemetry.go
pkg/tests/end_to_end_tests/drop_test.go
pkg/tests/end_to_end_tests/ha_single_promscale_test.go
pkg/tests/end_to_end_tests/ingest_trace_test.go
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
pkg/tests/end_to_end_tests/telemetry_test.go
pkg/tests/end_to_end_tests/trace_query_integration_test.go

This commit refactors the metric registration process in telemetry. Now,
the telemetry engine no longer requires to be passed down to each module
that wants to send telemetry, rather just expose a func which accepts a
telemetry engine.
The call of this exposed function happens in runner.go where all modules
that want to send telemetry are called and managed.
Fixes: #1156 

Refactors telemetry metric registration

---

pkg/pgmodel/ingestor/ingestor.go
pkg/pgmodel/ingestor/trace/writer.go
pkg/pgmodel/metrics/ingest.go

We use the size of received Protobuf message to calculate bytes.
Tracking ingested bytes is useful when comparing Promscale to competitors... 
Later on we might expose this in Telemetry but we need schema migration completed before.

Track number of ingested bytes for metrics and traces

---

.goreleaser.yml

goreleaser: Fix deprecated 'use_buildx'

---

CHANGELOG.md
pkg/runner/flags.go
pkg/runner/flags_test.go

This was not possible before with legacy HA, but was missed when
updating to non-legacy HA. It doesn't make sense to try to combine these
two operation modes.

Disable running Promscale in both HA and read-only mode

---

CHANGELOG.md
pkg/pgmodel/ingestor/trace/writer.go

Fixes: #1239
After the fix, the metric now looks like

Fix `promscale_ingest_max_sent_timestamp` value for traces.

---

CHANGELOG.md
cmd/promscale/main.go
docker-compose/docker-compose.yaml
docker-compose/test.sh
docs/configuration.md
pkg/runner/flags.go
pkg/runner/flags_test.go
pkg/util/util.go
scripts/end_to_end_tests.sh

We have deprecated flags that need to be removed for next release. This
change removes the flags but still attempts to detect usage of old flag
names and old environmental variable names and logs their usage with
recommendations to rename them to new names. Execution will stop if
any of the old names are used.
Fixes #1109 

Remove deprecated flags for new release

---

CHANGELOG.md
docs/dataset.md
pkg/dataset/config.go
pkg/dataset/config_test.go
pkg/dataset/duration.go
pkg/runner/client.go
pkg/tests/end_to_end_tests/config_dataset_test.go

This change adds more options to the existing one (metrics chunk interval) for
setting global dataset configuration using the `-startup.dataset.config` flag.
This makes it a bit easier to configure and maintain these settings vs.
doing it through the database directly.

Add Gitops dataset configuration options

---

CHANGELOG.md
pkg/tests/end_to_end_tests/continuous_agg_test.go

In [1] we fixed some typos in the `reset_metric_retention_period`
function which caused the function to break when used with two-step
continuous aggregates.
This change adds tests cases to exercise `reset_metric_retention_period`
with two-step aggregates.
[1]: https://github.com/timescale/promscale_extension/pull/180
- [] ~~Updated the relevant documentation~~

Add test case for `reset_metric_retention_period` with two-step agg

---

.github/workflows/go-e2e.yml
pkg/tests/upgrade_tests/upgrade_test.go

Addresses #1274 & #1257
The corresponding changes on the extension side need to be merged first https://github.com/timescale/promscale_extension/pull/171

Re-enabling PG12 tests.

---

.github/workflows/mixin.yml
CHANGELOG.md
Makefile
deploy/helm-chart/templates/prometheus-rule.yaml
scripts/generate-helm-alerts.sh

Adding a simple script that can copy-paste alerts from `docs/mixin` to a helm chart and wrap it in PrometheusRule object.
Feature is available only when user uses prometheus-operator and enables promscale ServiceMonitor.
This PR is focusing only on prometheus rules as there is no kubernetes-native way to provision grafana dashboard. This part will need to be done on tobs side where we have more control over provisioning grafana itself.

deploy/helm-chart: add automatic provisioning of alerts via helm chart

---

pkg/pgmodel/querier/query_builder.go
pkg/tests/end_to_end_tests/functions_test.go
pkg/tests/end_to_end_tests/sql_bench_test.go
pkg/tests/end_to_end_tests/telemetry_test.go

In [1] we set the default search path to only contain "public" schemas.
In particular, the two schemas "_prom_ext" and "_prom_catalog" are no
longer on the default search path.
This makes usages of those functions fully schema-qualified.
[1]: https://github.com/timescale/promscale_extension/pull/198

Adjust to handle new default search path

---

CHANGELOG.md
deploy/helm-chart/README.md
deploy/helm-chart/templates/config.yaml
deploy/helm-chart/templates/deployment-promscale.yaml
deploy/helm-chart/values.yaml

As in title. This allows setting dataset config values in helm chart values.yaml file.
This PR on purpose does not set all default values in a ConfigMap, but only a small subset. This is done to show that values can be set, but at the same time to reduce maintenance over the list of values.
Changing any value in `datasetConfig` will result in Promscale redeployment due to different checksum annotation.
Resolves https://github.com/timescale/o11y-team-applications/issues/185
Related to https://github.com/timescale/promscale/pull/1276
Please take into account the following non-code changes …

deploy/helm-chart: add ability to set dataset config parameters

---

.github/CODEOWNERS

Changes:
- Default codeownership is assigned to @o11y-applications sub-team
- Code ownership of every package that had just a single code owner is transferred to that persons sub-team
- Since I was creating renovate and dependabot pipelines, I am stepping up as a code owner of `go.sum` and `go.mod` alongside Ante.
- CI system and repository configuration ownership is transferred to Mat and myself
- Vineeth is removed from being a code owner due to position change
Those changes should allow better automatic reviewer assignment by GitHub and are in line with recent slack discussion.
cc …

.github: switch code ownership to subteams

---

CHANGELOG.md
docs/configuration.md
pkg/rules/config.go
pkg/rules/config_test.go
pkg/rules/rules.go
pkg/rules/testdata/alert_config.good.config.yaml
pkg/rules/testdata/no_rules.bad.config.yaml
pkg/rules/testdata/no_rules.good.config.yaml
pkg/rules/testdata/non_existent_rules.good.config.yaml
pkg/rules/testdata/rules.good.config.yaml
pkg/rules/testdata/rules.yaml
pkg/runner/flags.go
pkg/runner/runner.go

Fixes: https://github.com/timescale/o11y-team-applications/issues/180
This PR adds support for reading the Prometheus configuration file, validates it, and logs as per content in the file. Based on the details in configuration, it starts the rules-manager. This PR also contains tests for reading and validating Prometheus configuration.
Next PRs will be:
1. Implement the `/api/v1/rules` API
2. E2E tests for Rules-manager

Adds support for reading Prometheus config and links ruler with runner 

---

pkg/dataset/config.go
pkg/pgmodel/metrics/database/metrics.go
pkg/tests/end_to_end_tests/config_dataset_test.go

We refactored _prom_catalog.default and wrapped it with a getter/setter. This updates the connector code that directly accessed the table to use the getter/setter instead.
This PR corresponds to [this extension PR.](https://github.com/timescale/promscale_extension/pull/185)

Use getter/setters for default values

---

deploy/helm-chart/templates/secret-connection.yaml
deploy/helm-chart/values.yaml
deploy/static/deploy.yaml

Since tobs modify this secret to inject password, we need a way to not override those changes during tobs upgrades. 
This PR doesn't change anything for regular users, but allows setting user and password from external sources by manipulating the connection secret with other tools.

deploy/helm-chart: conditionally set password and user in connection secret

---

pkg/jaeger/query/get_operations.go
pkg/jaeger/query/trace_query.go

Recent changes in the Promscale extension introduced index on jsonb hash.

Filter on jsonb hash so planner can use index

---

.github/workflows/go-releaser.yml

This PR changes things so that pre-release tag packages are
sent to the timescaledb-exp package cloud repo and not
the standard ones.
Docker images are already correctly handled by the use of
skip_publish = auto for the latest and major.minor tags
in .goreleaser.yml
The github release is already created in draft.

Handle pre-release tags in CICD

---

.github/CODEOWNERS

As in the title. Adding Prem as an explicit owner of deployment models and monitoring mixin.

.github: add @onprem as code owner for deployment methods and monitoring mixin

---

CHANGELOG.md
pkg/pgmodel/new_migrate.go

As of version 0.11.0, Promscale extension is required for all operation.
This commit adds logging when upgrading from older versions that the latest
version of extension is missing and necessary to proceed.

Log mandatory requirement of Promscale extension when upgrading

---

.github/workflows/go-releaser.yml

We were previously only publishing packages for Debian. We now cover the
same Ubuntu versions as TimescaleDB and the Promscale Extension.
Closes #1341

Publish packages for ubuntu distros

---

pkg/pgmodel/ingestor/trace/writer.go

Reusing the temp table will reduce catalog bloat and logging. No need to recreate it continuously.

Reuse temp table for trace ingest

---

pkg/tests/end_to_end_tests/continuous_agg_test.go

With the timescaledb_toolkit extension being pre-installed in the
timescaledb-ha docker image, extension creation can fail. So now we
create the extension with `IF NOT EXISTS`.

Fix two-step aggregate tests

---

docker-compose/alerts.yml
docker-compose/docker-compose.yaml
docker-compose/high-availability/docker-compose.yaml
docker-compose/high-availability/prometheus1.yml
docker-compose/high-availability/prometheus2.yml
docker-compose/promscale_prometheus.yml
docker-compose/rules.yml

- Recording Rules and Alert example for normal and HA
- Alertmanager for normal and HA
- Fixed up HA to match HA in a bunch of ways
- scrape_configs
- database (timescale -> postgres)
- password
- db args -> connstring
This is the second take at this PR as I stuffed up the Git history for the first and it needs to be released ASAP (blog post out)

Rules+Alert config w/ Alertmanager & cleanup

---

Makefile

`find -type f -name '*.md'` does not work on "stock" macOS, and it's not actually needed anyway. This replaces the subshell usage of `find` in the makefile with a glob that produces the same result and allows us "stock" macOS users to run these make targets.
https://stackoverflow.com/questions/25840713/illegal-option-error-when-using-find-on-macos 

Use glob filter for mbox instead of find

---

docker-compose/high-availability/prometheus1.yml
docker-compose/high-availability/prometheus2.yml
docker-compose/high-availability/test.sh

It turns out that the HA test script was still working under the old HA
model, so it had to be reworked.

docker-compose: switch to using newer HA deployment model

---

go.mod
pkg/pgmodel/ingestor/dispatcher.go
pkg/pgmodel/ingestor/ingestor.go
pkg/pgmodel/ingestor/ingestor_test.go
pkg/rules/rules.go

We make sure to keep the state of ingest components and to block
race condition where component might be stopped but we still try
to ingest.
We also don't allow for closing of already closed components as that
can cause panic.
For rule manager we  wait for all group actors to stop before returning. Otherwise
a race condition might happen as sub components might continue running.

Manage stopping of ingest components

---

pkg/api/router.go

Load balancers prefer to make HEAD or OPTIONS requests for health checks
as they are cheaper.
Related https://github.com/timescale/promscale/issues/710
Also some community users encountered this problem  https://timescaledb.slack.com/archives/C011FC0PPC5/p1653384295441989?thread_ts=1652775715.500199&cid=C011FC0PPC5

Add HEAD and OPTIONS on healthz

---

pkg/jaeger/query/trace_scan.go
pkg/tests/end_to_end_tests/dataset_traces_test.go

open-telemetry collector does not have proper API support for slices so we
needed a different approach when it comes to processing JSON.
Closes https://github.com/timescale/promscale/issues/1379

Support slices in traces attributes

---

.github/workflows/helm.yml
CHANGELOG.md
deploy/helm-chart/templates/deployment-promscale.yaml
deploy/static/deploy.yaml

Adding readiness probe to use `/healthz` endpoint as a source of information for kubernetes traffic steering (by default kubernetes won't allow traffic flow to pod that is unhealthy).

deploy/helm-chart: add readinessProbe

---

pkg/tests/end_to_end_tests/metric_ingest_bench_test.go
pkg/tests/testsupport/metric_loader.go

Allow loading the whole test data set into memory which can be useful when
benchmarking memory allocations. It also helps avoid any i/o related issues 
when loading chunk data in streaming fashion (Prometheus uses mmap files), although
I haven't see any so far (the numbers are just slightly better when ingesting from memory)
Don't block on sending ingest requests while creating batches which improves
data load speed.
I've also tried using sync Pool to ease GC, however it slowed down the benchmark so I gave up on that (which makes sense since sync.Pool requres more CPU work then just creating new instance)

Tweaks for local go bench

---

CHANGELOG.md
pkg/pgclient/config.go

Promscale extension now exposes the number of CPUs that are available to
the database. We can use this information to set the appropriate number of
copiers so we can utilize the database in an efficient manner.

Set number of copiers based on DB CPU count

---

CHANGELOG.md
pkg/pgclient/client.go
pkg/pgmodel/lreader/labels_reader.go
pkg/pgmodel/lreader/labels_reader_test.go
pkg/pgmodel/querier/querier_sql_test.go
pkg/runner/runner.go
pkg/tests/end_to_end_tests/continuous_agg_test.go
pkg/tests/end_to_end_tests/exemplar_test.go
pkg/tests/end_to_end_tests/main_test.go
pkg/tests/end_to_end_tests/multi_tenancy_test.go
pkg/tests/end_to_end_tests/nan_test.go
pkg/tests/end_to_end_tests/null_chars_test.go
pkg/tests/end_to_end_tests/promql_label_endpoint_test.go
pkg/tests/end_to_end_tests/query_integration_test.go

If allowed tenants are configured we only list those when showing `__tenant__` values.
Fixes https://github.com/timescale/promscale/issues/1194

List label values of allowed tenants only

---

CHANGELOG.md
deploy/helm-chart/templates/deployment-promscale.yaml
deploy/static/deploy.yaml

As in title.
Tobs will use `TOBS_TELEMETRY_INSTALLED_BY: "tobs"` for helm installation.

deploy/helm-chart: (ab)use telemetry to check how many people use promscale helm chart directly

---

go.mod
go.sum
pkg/pgmodel/ingestor/dispatcher.go
pkg/pgmodel/ingestor/metric_batcher.go
pkg/pgmodel/ingestor/metric_batcher_test.go
pkg/tests/end_to_end_tests/alerts_test.go
pkg/tests/testdata/rules/alerts.yaml
pkg/tests/testdata/rules/config.alertmanager.yaml
pkg/tests/testdata/rules/config.alerts.yaml

This commit mimics a case of actual alerting + alertmanager.
It starts the rules-manager with a alert that is always firing.
Then, in E2E test, we start a mock alertmanager server in the `alertsReceiver()`
which listens for alerts just as the alertmanager does. We send down a channel
to this server that signals whether we received an expected alert or not, which
decides the fate of the test.
All references are linked in the commit.

Adds E2E test for alerting in Promscale.

---

CHANGELOG.md
pkg/api/reload.go
pkg/api/router.go
pkg/rules/rules.go
pkg/runner/runner.go
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
pkg/tests/end_to_end_tests/rules_test.go
pkg/tests/testdata/rules/config.empty_rules.yaml

Fixes: https://github.com/timescale/o11y-team-applications/issues/182

Adds support for reloader in Promscale.

---

.github/renovate.json

Right now renovate knows how to match extension version to a file, but without the change in this PR it doesn't know what to do with that match.

.github: add extension group to renovate

---

CHANGELOG.md
docs/mixin/dashboards/promscale.json
docs/runbooks/PromscaleDBHighErrorRate.md
docs/runbooks/PromscaleIngestHighLatency.md
pkg/pgmodel/metrics/database/database.go
pkg/pgmodel/metrics/database/metrics.go
pkg/runner/runner.go

Fixes: https://github.com/timescale/o11y-team-applications/issues/194
This PR adds a Prometheus metric that tracks the network latency from Promscale to the database.

Adds support for network latency metric.

---

.github/renovate.json

This was tested using [renovate docker image](https://hub.docker.com/repository/docker/renovate/renovate) and [my forked repository](https://github.com/paulfantom/promscale/pulls).
Process was as follows:
1. `docker pull renovate/renovate`
2. `docker run -it renovate/renovate bash`
3. From now on all commands were executed in the docker container and changes to the repository were done in a separate terminal by pushing commits to `master` branch.
4. `renovate timescale/promscale --dry-run --token $GH_TOKEN` which failed spectaculary
5. `renovate paulfantom/promscale --renovate-fork …

.github: do not assign extension update to any group

---

pkg/pgmodel/cache/series_cache.go
pkg/pgmodel/cache/series_cache_test.go
pkg/pgmodel/ingestor/ingestor.go
pkg/pgmodel/ingestor/series_writer.go
pkg/pgmodel/model/series.go

- Some comments reference structs or methods which have been renamed
- Change parameter name from 'builder' to 'keyBuffer' in `generateKey`
- Remove double-creation of key and value in series_writer.go

Minor refactoring for clarification

---

.github/renovate.json

Disabling Renovate to update Go deps temporarily to reduce the amount of
maintenance time necessary to keep them up to date. This should be re-enabled
once we reach a more stable point in the project (e.g. version 1.0).

Disable Renovate bot for managing Go dependencies

---

.github/workflows/go-e2e.yml
EXTENSION_VERSION
pkg/pgmodel/common/schema/schema.go
pkg/pgmodel/ingestor/copier.go
pkg/pgmodel/ingestor/ingestor_sql_test.go
pkg/pgmodel/ingestor/trace/writer.go
pkg/pgmodel/model/sql_test_utils.go
pkg/pgxconn/pgx_conn.go
pkg/telemetry/telemetry_test.go
pkg/tests/end_to_end_tests/concurrent_sql_test.go
pkg/tests/end_to_end_tests/ha_single_promscale_test.go
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
pkg/tests/testsupport/metric_loader.go

We try COPY into metric table. If there is a conflict situation
(eg. duplicate key violation) we catch it on client and retry
by COPYing to temporary table and doing ON CONFLICT insert from there.

Ingest metric data with COPY to get better performance

---

pkg/pgmodel/ingestor/dispatcher.go
pkg/pgmodel/ingestor/metric_batcher.go

In few instances, string data type has been forced on int data. This commit just fixes those.

Use correct data types in otel span attributes

---

docs/mixin/.lint
docs/mixin/dashboards/apm-home.json
docs/mixin/dashboards/apm-service-overview.json

Update APM dashboards trace reference URLs. As the default version of Grafana in tobs is `9.0.2` this requires trace reference URLs to be updated.

Fix APM dashboards trace refs

---

pkg/tests/end_to_end_tests/drop_test.go

This PR disables `TestSQLDropMetricChunk` test so that changes in https://github.com/timescale/promscale_extension/pull/396 can be merged. Once that PR goes in, this test can be enabled after necessary modifications.

Disable test `TestSQLDropMetricChunk`.

---

CHANGELOG.md
docs/runbooks/PromscaleCompressionLow.md
pkg/pgmodel/metrics/database/metrics.go
pkg/tests/end_to_end_tests/database_metrics_test.go

`PromscaleCompressionLow` alert fires regardless of a good compression ratio.
SQL query which populates `promscale_sql_database_chunks_count` is a sum of the below metrics,
1) Uncompressed Chunks
2) Proxy Chunks which points to Compressed Chunks
3) Compressed Chunks
However the total chunk count should be just (1) + (3), because (2) is already pointing to (3) and which leads to double counting.
Fix the SQL query to consider entries which has `compressed_chunk_id` as null and this will be true for both (1) and (3).

Fix double counting while populating `promscale_sql_database_chunks_count` metric

---

docker-compose/docker-compose.yaml
docker-compose/high-availability/docker-compose.yaml
docker-compose/high-availability/prometheus1.yml
docker-compose/high-availability/prometheus2.yml
docker-compose/high-availability/test.sh
docker-compose/prometheus.yml
docker-compose/promscale-demo/docker-compose.yaml

Update the docker-compose to make it simple, The quick start guide specifically had a few unnecessary configs and heavy-weight configurations on the quick guide. In this I'm modifying the below list of configurations:
1. Change the load generator replicas from 3 to 1.
2. Updated default database name from `otel_demo` to `tsdb`.
3. Drop metrics path configuration to default i.e. from `/metrics-text` to `/metrics`.
4. Add telemetry env for Promscale to `docker-quick-start`. This helps to gauge user engagement.

Update the docker-compose

---

Makefile

Multinode is not supported and running the e2e tests with the flag
causes the following error when creating the extension:
```
CREATE EXTENSION IF NOT EXISTS promscale VERSION '0.5.4';
ERROR:  [dn0]: schema "ps_trace" does not exist
```

Remove multinode e2e tests from the e2e target

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/benchmark.yaml
pkg/log/log.go
pkg/promql/bench_test.go

This PR adds the support for running benchmarks in Promscale on CI. It also compares with the benchmark results of the master branch.
By default, benchmarks will not be active when a PR (or draft PR) is opened. A dev has to assign `action:benchmarks` label, which will automatically trigger the benchmark workflow.
In order to restart the benchmarks, just remove and reassign the label, and it will trigger the benchmark workflow again.
Note:
1. After the benchmark comparison with benchstat is done, the results will be pasted as a PR comment, tagging the author. Each PR comment with a result contains the code hash corresponding to which the benchmark was executed.2. 
2. The commenting on PR will happen only if the PR is opened from a branch in Promscale repo, not from your fork. This is due …

Adds support to run and compare benchmarks on CI

---

pkg/tests/end_to_end_tests/metric_ingest_bench_test.go
pkg/tests/testsupport/series_gen.go

This PR adds benchmarks for new series creation case. This happens when Promscale sees a new series for the first time, like in case of a startup.
The `NewSeriesGenerator` creates batches of distinct series based on the given `numMetrics` and `numSeries`, with each series containing labels equal to `labels` arg of the function. The label key in the series remain constant, and the value always changes to create a new series.

Adds support for benchmarking new series creation.

---

pkg/tests/upgrade_tests/upgrade_test.go

Fix upgrade test by pinning to timescaledb 2.7.1

---

.github/workflows/helm.yml
deploy/helm-chart/templates/deployment-promscale.yaml
deploy/helm-chart/values.yaml
deploy/static/deploy.yaml

In the Helm chart we are not forcibly setting a container image version, which will always pull the `latest` tag.  The changes here will set the image tag from `Chart.yaml` but allow override from `values.yaml` if the end user wants to use a different tag.
- Change how the container image information is structures in
values.yaml
- Take the default container image tag from Chart.yaml, but allow
override.

Helm pin version

---

pkg/pgxconn/pgx_conn.go

fix pass []any as any in `Next`, call `logQueryStats` need with `args...`
and fix logQueryStats `fmt.Sprintf("%v", args...)` if args has many this will not format as expected.
see github actions result here https://github.com/alingse/asasalint/runs/7270916179?check_suite_focus=true

fix pass []any as any in `logQueryStats`

---

pkg/pgmodel/ingestor/trace/cache.go
pkg/runner/runner.go

Prometheus metrics has to be registered after all services are added
Enabling server histograms should be done before registering metrics.
Bumping tag cache size since 10K seems pretty low.

Prometheus metrics has to be registered after all services are added

---

migration-tool/cmd/prom-migrator/README.md

Because VictoriaMetrics doesn't support remote read, it doesn't allow users to use prom-migrator to migrate data from it to another Prometheus compatible-backend. The README wrongly stated that VictoriaMetrics supported remote read.

VictoriaMetrics doesn't support remote read

---

.github/PULL_REQUEST_TEMPLATE.md

We've had some issues that were in the ‘open’ state despite having the ‘Merged/Done’ status. There's no automation in github projects yet for closing issues in that status. Thus, this commit expands the template by examples of how exactly one can link an issue to the pull request. The linked issues are closed automatically when the pull request is on the default branch.
*Note: If your PR involves benchmarks, you can run the `Benchmarks` workflow by adding `action:benchmarks` label. The PR must be opened from Promscale branch so that Github actions can leave a comment comparing results …

Expand the reminder to link issues to PRs

---

.github/workflows/helm.yml
deploy/helm-chart/templates/deployment-promscale.yaml
deploy/helm-chart/values.yaml
deploy/static/deploy.yaml

Cherry pick commit from 60062e06 
- Change how the container image information is structures in values.yaml
- Take the default container image tag from Chart.yaml, but allow override.
- Fix github actions pipeline

Ensure we pin the container image of Promscale to an actual version

---

CHANGELOG.md
pkg/pgmodel/Readme.md
pkg/pgmodel/cache/inverted_labels_cache.go
pkg/pgmodel/ingestor/dispatcher.go
pkg/pgmodel/ingestor/ingestor_sql_test.go

The database cache epoch advances when series are deleted from the
database. When connector detects a cache epoch change, it invalidates
the series cache, as it may contain values which reference the deleted
rows in the series table.
During the database series deletion, unused labels may also be deleted.
This means that we must also invalidate the inverted label cache, as it
could also reference deleted rows in the `_prom_catalog.label` table.

Reset inverted labels cache on epoch change

---

CHANGELOG.md
pkg/pgmodel/ingestor/copier.go
pkg/tests/end_to_end_tests/exemplar_test.go

Fixes: #1567 
This PR fixes the `ERROR: column \"exemplar_label_values\" does not exist (SQLSTATE 42703)` error seen in exemplar ingestion. Based on what I studied, the error occurred due to temporary tables created for samples being used for exemplars as well. Exemplars have a different column requirements and hence the error.

Fix: Exemplar ingestion due to conflicting temporary tables.

---

pkg/version/version.go

We must relax the extension version constraints in order for the
extension's release tests to pass. The constraints can be tightened
once the new version of the extension is release.

Allow using version 0.6.0 of the Promscale extension

---

.github/PULL_REQUEST_TEMPLATE.md

The instructions are meant to be seen when editing the PR description,
but serve no purpose once the description has been created. Putting them
in a HTML comment hides them.

Hide PR template instructions from published PR

---

pkg/tests/end_to_end_tests/metric_ingest_bench_test.go
pkg/tests/testsupport/series_gen.go

This commit adds benchmark to test ingestion performance with varying series count and batches.
Related to https://github.com/timescale/promscale/issues/1530
*Note: If your PR involves benchmarks, you can run the `Benchmarks` workflow by adding `action:benchmarks` label. The PR must be opened from Promscale branch so that Github actions can leave a comment comparing results against `master`.*

Add benchmark to test varying ingestion load

---

pkg/internal/testhelpers/containers.go
pkg/tests/upgrade_tests/upgrade_test.go

For some reason, we have never allowed the database container to cleanly shutdown.

Fix upgrade test by cleanly stopping test containers

---

pkg/runner/runner.go

context.Canceled is returned by grpc stream.Recv when you stop promscale with Ctrl-C.Skip logging the above error as the behavior is expected.

Skip context.Canceled error in grpc logging interceptors

---

CHANGELOG.md
pkg/clockcache/cache.go
pkg/clockcache/cache_test.go

The clockcache is a simple approximation of an LRU cache. Instead of
maintaining an exact ordering of which elements were least recently
used, the cache simply keeps track of whether each element is "used".
When an item is inserted into the cache, it is counted as unused. When
an item is fetched from the cache, it is counted as used.
The eviction algorithm looks through the elements of the cache one by
one, trying to find one to evict. If the item is used, it marks it as
unused. If it is unused, it can evict the item. The next time an
eviction is required, it can continue with the next element.
Through a bug in index manipulation, if the next item to be evicted was
at index 1 of the storage array, the next eviction would not continue to
index 2. Instead, after successfully evicting an …

Fix broken cache eviction in clockcache

---

pkg/runner/runner.go

Since `context.Caceled` is declared as:
```
var Canceled = errors.New("context canceled")
```
We should use `errors.Is` instead of `errors.As` because we are
comparing against and error value instead of the type of the error.
golangci-lint reports the current usage of `errors.As` with the
following error:
```
golangci-lint run
pkg/runner/runner.go:61:20: errorsas: second argument to errors.As should not be *error (govet)
if err != nil && !errors.As(err, &context.Canceled) {
^
pkg/runner/runner.go:69:20: errorsas: second argument to errors.As should not be *error (govet)
if err != nil && !errors.As(err, &context.Canceled) {
```

Compare for context.Canceled error with `Is`

---

migration-tool/pkg/integration_tests/remote_reader_test.go
migration-tool/pkg/integration_tests/remote_writer_test.go
migration-tool/pkg/utils/client.go
pkg/api/common.go
pkg/api/common_test.go
pkg/api/delete_test.go
pkg/api/parser/json/json_test.go
pkg/api/parser/parser_test.go
pkg/api/parser/text/text.go
pkg/api/query_exemplar_test.go
pkg/api/read.go
pkg/internal/testhelpers/containers.go
pkg/internal/testhelpers/containers_test.go
pkg/limits/flags_test.go
pkg/pgmodel/cache/flags_test.go
pkg/promql/engine_test.go
pkg/promql/query_logger_test.go
pkg/promql/test.go
pkg/runner/flags_test.go
pkg/tenancy/flags_test.go
pkg/tests/end_to_end_tests/alerts_test.go
pkg/tests/end_to_end_tests/datasets_metrics_test.go
pkg/tests/end_to_end_tests/golden_files_test.go
pkg/tests/end_to_end_tests/prometheus_wal_test.go
pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
pkg/tests/end_to_end_tests/promql_write_endpoint_test.go
pkg/tests/end_to_end_tests/query_integration_test.go
pkg/tests/end_to_end_tests/trace_query_integration_test.go
pkg/tests/upgrade_tests/shapshot.go
pkg/tests/upgrade_tests/upgrade_test.go

From the docs https://pkg.go.dev/io/ioutil as of Go 1.19 the package has
been deprecated.
> Deprecated: As of Go 1.16, the same functionality is now provided by
> package io or package os, and those implementations should be preferred
> in new code. See the specific function documentation for details.

Move from deprecated ioutil to io and os

---

CHANGELOG.md
pkg/jaeger/proxy/proxy.go

Using unbuffered channels to receive in a select block might lead to a
goroutine leak if another branch of the select is selected instead.
By using a buffered channel the writer doesn't have to wait for another
goroutine to unblock it with a read. Instead it just uses the buffered
space to send the message and continue its execution.
fixes #1604 

Fix possible goroutine leak

---

CHANGELOG.md
pkg/api/delete.go
pkg/api/label_values.go
pkg/api/labels.go
pkg/api/metadata.go
pkg/api/query_test.go
pkg/api/read.go
pkg/api/read_test.go
pkg/pgclient/client.go
pkg/pgclient/client_test.go
pkg/pgmodel/delete/delete.go
pkg/pgmodel/metadata/metadata.go
pkg/pgmodel/querier/common.go
pkg/pgmodel/querier/interface.go
pkg/pgmodel/querier/querier.go
pkg/pgmodel/querier/querier_sql_test.go
pkg/pgmodel/querier/query_exemplar.go
pkg/pgmodel/querier/query_remote_read.go
pkg/pgmodel/querier/query_sample.go
pkg/pgmodel/querier/query_tools.go
pkg/query/queryable.go
pkg/tests/end_to_end_tests/db_connections_test.go
pkg/tests/end_to_end_tests/delete_test.go
pkg/tests/end_to_end_tests/metadata_test.go
pkg/tests/end_to_end_tests/multi_tenancy_test.go
pkg/tests/end_to_end_tests/nan_test.go
pkg/tests/end_to_end_tests/null_chars_test.go
pkg/tests/end_to_end_tests/query_integration_test.go

Each http.Request comes with its own context, in the case the client
connection closes this context is cancelled.
Propagating the request context prevents the request handler from doing
extra work in situations when the client is not going to be able to
receive the response.
For supporting context propagation, the same approach from the
Prometheus codebase was followed. Every `Queryable` method that returns
a `Querier` accepts a context, it's the `Querier` responsibility to
propagate it downstream.
- Prometheus `Queryable` interface definition:
https://github.com/prometheus/prometheus/blob/15fa34936b6f1febe896ecee0f49889a56347762/storage/interface.go#L79-L84
- Prometheus `Querier` propagating the ctx in the `Select` method:
https://github.com/prometheus/prometheus/blob/15fa34936b6f1febe896 …

Propagate context from query requests

---

pkg/internal/testhelpers/prometheus_container.go

There's a problem with the main tag. When a container is started it
fails with the following error:
Error setting up container Error response from daemon: failed to create shim
task: OCI runtime create failed: runc create failed: unable to start
container process: exec: "/bin/prometheus": permission denied: unknown:
failed to start container.

Unblock CI by using latest instead of main for prom/prometheus in e2e

---

pkg/internal/testhelpers/prometheus_container.go

Reverts timescale/promscale#1628
The issue with main was fixed 
https://github.com/prometheus/prometheus/issues/11286

Revert "Unblock CI by using latest instead of main for prom/prometheus in e2e"

---

CHANGELOG.md
pkg/runner/runner.go
pkg/telemetry/telemetry.go
pkg/tests/end_to_end_tests/telemetry_test.go

Fixes: #1413 
This commits updates the telemetry engine to start, irrespective of
whether `timescaledb.telemetry_level` is `on` or `off`. However,
collection of telemetry happens only when the `telemetry_level` is `on`.
This allows the telemetry engine to either start telemetry collection
if it was disabled in the starting, but enabled later on, or stop
telemetry collection if it was enabled in the starting but disabled
later on.

Fix: Do not collect telemetry if set to `off`

---

CHANGELOG.md
pkg/util/throughput/throughput.go

Fixes: #1642 
This commit fixes `0 samples/sec` logging in throughput. The reason behind this behaviour was metric-metadata not being printed, rather it was just updating the `metrics-max-ts-send`, which was causing the log.
This `metrics-max-ts-send` was updated even when we were writing metadata.
Now, the log for metric, metric-metadata and spans will be in single line, compared to the earlier separate lines.
```shell
level=info ts=2022-09-14T07:36:34.072Z caller=throughput.go:90 msg="ingestor throughput" samples/sec=80000 metrics-max-sent-ts="2022-09-14 07:36:13.178 +0000 UTC" metric-metadata/sec=249
level=info ts=2022-09-14T07:40:17.419Z caller=throughput.go:90 msg="ingestor throughput" samples/sec=64223 …
```

Fix: `0 samples/sec` in throughput by logging metric metadata throughput

---

pkg/jaeger/store/trace_query.go
pkg/tests/end_to_end_tests/trace_query_integration_test.go

When searching for tags in jaeger, a tag can come from any event attached to a span. Different tags can come from different events on the same span. Previously, this was broken since the events were joined to spans and tags searched one-at-a-time.
Fixed this by searching with EXISTS.

Fix event tag correctness

---

CHANGELOG.md
pkg/pgmodel/new_migrate.go

In some cases, an extension upgrade is a multi-step process. This change wraps some of those steps in an explicit transaction. Specifically, we don't want a failure to result in the extension being left at version 0.0.0

Wrap extension upgrades in a transaction

---

pkg/pgmodel/common/schema/schema.go

This magic number is used in the promscale and promscale_extension codebases. In the promscale_extension codebase it's formatted as a decimal number. For the sake of more easily being able to find this number across the different codebases, we should format it the same.

Format advisory lock ID as decimal number

---

CHANGELOG.md
pkg/jaeger/store/store.go
pkg/runner/runner.go

- NotFound is returned, for example, when querying a Trace and the trace is not found.
- Canceled when the context is canceled.
Before we were checking the errors for context.Canceled but gRPC doesn't wrap the errors, it just creates an Status object that contains the error message. 

Do not log gRPC NotFound and Canceled status code

---

CHANGELOG.md
pkg/jaeger/store/binary_tags.go
pkg/jaeger/store/binary_tags_test.go
pkg/jaeger/store/find_traces.go
pkg/jaeger/store/store.go

Since we are using the OTEL translator, when ingesting Jaeger traces all
the tags with `VType=ValueType_BINARY` are being encoded into base64 and
stored as strings. The context of the type of value is lost after this
translation occurs, meaning that, when we return those tags in a Jaeger
query we return the base64 string as `VType=ValueType_STRING`.
To preserve the type of the value, the prefix
`data:application/octet-stream; base64,` will be added to the base64
string before storing in the DB. When retrieving a trace we look for
tags that are string and have this prefix, we remove it and return a
`ValueType_BINARY` with the result of decoding the base64 string.
The prefix was choosen from the `The "data" URL scheme` RFC
https://www.rfc-editor.org/rfc/rfc2397#section-2 .
Jaeger allows …

Support for Jaeger tags with binary value

---

CHANGELOG.md
pkg/pgmodel/ingestor/copier.go
pkg/pgmodel/ingestor/ingestor_sql_test.go

Currently, the temp tables used for ingestion are named using a transient value. This PR substitutes the transient value for the metric_id. This change creates a temp table specific to the metric and database session, allowing it to be reused.
The temp table is currently created with ON COMMIT DROP, which requires that the temp table be recreated with each transaction. This incurs significant pg_catalog churn/bloat. A corresponding PR will be made in the extension to change this to ON COMMIT DELETE ROWS.

Reuse ingestion temp tables across batches

---

.github/workflows/go-e2e.yml
Makefile
pkg/tests/end_to_end_tests/jaeger_store_integration_test.go

Prior to this PR Jaeger storage tests used to run as part of promscale e2e job.
Now it has been modified to run Jaeger tests in a dedicated job for a better visibility and easy auditing.

Run Jaeger storage integration tests in separate GH actions job

---

.github/CODEOWNERS
.github/renovate.json
ct.yaml

This is just a repository cleanup PR.
- Moved CI and repository configuration ownership solely to Applications team (as it de-facto was for the last months)
- Specified ownership of github action workflow related to monitoring mixin (mixin is owned by the services team)
- Removed Services ownership of `deploy/` directory as helm chart was moved
- Cleaned configurations related to helm

.github: clean up code ownership

---

pkg/jaeger/store/trace_query.go

Improves trace id query performance. 
Fixes #1540.
Blocked by #1621. After #1621 is resolved, rebase and reapply these patches. Keep as draft until then.

Improve trace id query

---

docs/runbooks/PromscaleMaintenanceJobRunningTooLong.md

When going through this runbook, i found what I assume is a mixup of `_interval` and `_chunks`, since the former would be, of course, an interval, and the latter seems to fit better with the context.
My apologies if I'm wrong, and I really appreciate these well-written runbooks!

Fix typo (?) in MaintenanceJobRunningTooLong runbook

---

docs/mixin/.lint
docs/mixin/dashboards/promscale.json

The `Requests (gRPC)` panel in the promscale dashboard was only showing handled requests by the OTEL collector. To include the metrics from the native Jaeger ingest endpoints are adding up 2 more metrics.
We are switching to the metric`grpc_server_msg_received_total` because of the way streaming works. Streaming allows to send/receive multiple messages on a single connection, so we need to count the amount of messages received and not the connection that were handled.

Include Jaeger ingest metrics in promscale dashboard

---

CHANGELOG.md
pkg/vacuum/vacuum.go

The log messages emitted by the vacuum engine were too verbose. This change makes some logs debug which were info.

Change log level in vacuum engine

---

pkg/clockcache/cache.go
pkg/clockcache/cache_bench_test.go
pkg/clockcache/cache_test.go
pkg/pgmodel/cache/series_cache.go
pkg/pgmodel/cache/series_cache_test.go

Approach is using timestamps to have better understanding on what elements are getting evicted. 
If we see an eviction of recently used/inserted element (defined with `evictionMaxAge`) we will attempt to grow the cache. 
`evictionMaxAge` defines max age where we are doing evictions and not growing the cache.
We don't use additional memory to track timestamps but re-use existing field by bit packing data into `uint32`.
Closes https://github.com/timescale/promscale/issues/1389

Fix series cache growth

---

pkg/tests/end_to_end_tests/functions_test.go

This test is no longer needed on the connector side. It is covered on the extension side, and it is blocking pending changes in the extension.

Remove TestMetricView

---

docs/mixin/.lint
docs/mixin/dashboards/.lint
docs/mixin/dashboards/promscale.json

This PR is improving dashboard in the following ways:
1) `Overview` and `Database` rows now contain panels. Previously they were empty in code which caused UX issues with row collapsing
2) Maintenance jobs graphs are moved to an additional section
3) Datasource can be now selected instead of using only one. As a side effect, we have only one place in code to set datasource UID.
4) All queries have `namespace` selector which defaults to `.+`. This improves workflow in kubernetes environments with multiple promscale-connectors. It doesn't affect environments without `namespace` label key present.

docs/mixin: add variables to promscale dashboard

---

docs/mixin/dashboards/promscale.json

This fixes issues introduced in #1731 where panels in "Overview" and "Database" rows weren't present in Grafana while being present in code.
Additionally this is also removing `__input` of `DS_PROMETHEUS` as datasource is now dynamically populated from metrics.
I tested this using grafana shipped with tobs as well as standalone grafana.

docs/mixin/dashboards: fix hidden panels and stop requiring DS variable

---

docs/mixin/dashboards/promscale.json

This PR fixes typo in dashboards causes incorrect graph rendering of P95, P90 in few panels.

Fix incorrect histogram quantile in promscale dashboard

---

docs/mixin/dashboards/promscale.json

Improvements:
- Ingest row is split into 2 separate ones (one for gRPC, one for HTTP)
- Cache is now in two rows (one for metrics, second for traces)
- All rows are collapsed for easier initial navigation
- Query is also showing p95 graph in duration panel to align with other panels.

docs/mixin: improve promscale dashboard

---

.github/renovate.json

Renovate knows about golang versions, but it doesn't know to bump the version in a Dockerfile.

Tell renovate about golang versions in Dockerfiles

---

.github/workflows/benchmark.yaml
.github/workflows/go-e2e.yml
.github/workflows/integration.yml

The `::set-output` pattern is deprecated [1], and has been replaced with piping the results to a specific file.
[1]: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Replace deprecated github actions '::set-output' command

---

CHANGELOG.md
docs/vacuum.md
pkg/runner/flags_test.go
pkg/runner/runner.go
pkg/tests/end_to_end_tests/vacuum_test.go
pkg/vacuum/vacuum.go
pkg/vacuum/vacuum_test.go

Throttle vacuum workers based on chunk age. Figure out how many workers to used based on the oldest transaction id age of the chunks in our batch. The age should be between `vacuumFreezeMinAge` and `autovacuumFreezeMaxAge`. The closer the `maxChunkAge` is to the `autovacuumFreezeMaxAge`, the more workers we assign. If `maxChunkAge` is == `vacuumFreezeMinAge`, then we just use 1 worker.
```
vacuumFreezeMinAge
|              maxChunkAge
|               |       autovacuumFreezeMaxAge
0-------|---------------X--------|------
1000            6789     11000
```
In this example, `maxChunkAge` is 57.89% of the way between `vacuumFreezeMinAge` and `autovacuumFreezeMaxAge`. If `maxParallelism` is 5, then we will use 3 workers.
If the autovacuum engine beats us to a chunk, skip that chunk.
Please …

Throttle vacuum workers based on chunk age

---

CHANGELOG.md
docker-compose/docker-compose.yaml
docker-compose/high-availability/docker-compose.yaml
pkg/clockcache/cache.go
pkg/pgmodel/cache/series_cache.go
pkg/pgmodel/ingestor/buffer.go
pkg/pgmodel/ingestor/copier.go
pkg/pgmodel/ingestor/dispatcher.go
pkg/pgmodel/ingestor/handler_test.go
pkg/pgmodel/ingestor/ingestor.go
pkg/pgmodel/ingestor/ingestor_sql_test.go
pkg/pgmodel/ingestor/metric_batcher.go
pkg/pgmodel/ingestor/metric_batcher_test.go
pkg/pgmodel/ingestor/series_writer.go
pkg/pgmodel/model/batch.go
pkg/pgmodel/model/batch_visitor.go
pkg/pgmodel/model/series.go
pkg/pgmodel/model/sql_test_utils.go
pkg/rules/adapters/ingest.go
pkg/tests/end_to_end_tests/create_test.go
pkg/tests/end_to_end_tests/drop_test.go
pkg/tests/upgrade_tests/shapshot.go
scripts/end_to_end_tests.sh

This change implements invalidation of the series cache, and mechanisms to prevent the ingestion of data based on stale cache information.
In principle, the cache invalidation mechanism works as follows:
In the database, we track two values: `current_epoch`, and `delete_epoch`. These are unix timestamps (which, for reasons of backwards-compatibility, are stored in a BIGINT field), updated every time that rows in the series table are deleted. `current_epoch` is set from `now()`, and `delete_epoch` is set from `now() - epoch_duration`. `epoch_duration` is a configurable parameter. 
When a series row is to be deleted, instead of immediately deleting it, we set the `delete_epoch` column of the series row to the `current_epoch` timestamp (the time at which we decided that it will be deleted). …

Implement series cache invalidation

---

pkg/clockcache/cache.go
pkg/clockcache/cache_bench_test.go
pkg/clockcache/cache_test.go

Recent benchmarks are showing that cache element alignment doesn't make significant compute difference. I've run benchmarks on Intel x86 CPUs and compute difference was either non or around 5%. Since cache usually holds millions of elements the cost seems to be higher than the gain.
Benchmark numbers and discussion: https://github.com/timescale/promscale/pull/1705#discussion_r1003237384
Closes https://github.com/timescale/promscale/issues/1717

Removing 16 bytes alignment for cache elements

---

specs/cache.cfg
specs/cache.tla

The cache invalidation model began its life in the https://github.com/timescale/promscale_specs repo. I have rewritten the history in that repository from the current master commit ([c3c2885](https://github.com/timescale/promscale_specs/commit/c3c2885834ae7803fb781e45818386aaee9b8d0f)) using the following command on the branch `rewrite-into-subdir`:
```bash
git filter-repo --force \
--path cache.cfg \
--path cache.tla \
--path-rename cache.cfg:specs/cache.cfg \
--path-rename cache.tla:specs/cache.tla
```
Subsequently, I added my local checkout of the `promscale_specs` repository as a remote, and merged that branch into promscale `master`:
```
git remote add spec ../promscale_specs
git fetch spec
git merge --allow-unrelated-histories spec/rewrite-into-subdir
```
Please take into account …

Merge specs

---

docs/mixin/alerts/alerts.yaml

Based on our experience `PromscaleStorageHighErrorRate` alert shouldn't include `exec` method as this is an outlier and only causes false-positive alerting. Additionally it would be beneficial to group Storage alerts by `method` so it is clearer who is the offender.
While fixing the above I noticed discrepancy in naming of our Storage/DB alerts, so I changed name of one alert from `PromscaleDBHighErrorRate` to `PromscaleStorageHighErrorRate` to align with other alerts and I also simplified this alert a bit.

Adjust Storage alerts

---

docs/mixin/.lint
docs/mixin/dashboards/promscale.json

This is preventing flat lines in some charts like "error rate" when there is actually data.

Dashboard min range

---

docker-compose/promscale-demo/docker-compose.yaml

Fix docker-compose, The Jaegerservice name is changed to `jaeger-all-ib-one` but the dependency name is still `jaeger`. Update the dependency name to `jaeger-all-in-one`. 

fix docker-compose

---

docker-compose/docker-compose.yaml

With the default configuration, Jaeger cannot connect to Promscale.
```
level=info ts=2022-11-20T01:06:24.418Z caller=runner.go:86 msg="Version: 0.16.0, Commit Hash: 72c29aa887517dcebc4b47a3d9fbb3ce3ac78450, Branch: HEAD"
level=error ts=2022-11-20T01:06:25.428Z caller=runner.go:127 msg="aborting startup due to error" err="failed to connect to `host=db user=postgres database=postgres`: dial error (dial tcp 192.168.96.4:5432: connect: connection refused)"
```
This PR aims to fix that by replacing the --grpc-storage.server argument to use environment variables.

Fix jaeger env vars in docker-compose.yaml

---

pkg/pgmodel/cache/series_cache.go

This means less re-allocations and less evictions when cache needs to grow.
Promscale memory usage on start will increase from 120MB to 360MB.

Bump series cache default size

---

pkg/tests/end_to_end_tests/create_test.go

This PR adds a test triggering the background job and eviction simultaneously with a randomized overlap.

Cache invalidation interleaving test

---

pkg/pgclient/client.go
pkg/pgmodel/cache/cache.go
pkg/pgmodel/cache/flags.go
pkg/pgmodel/cache/inverted_labels_cache.go
pkg/pgmodel/cache/series_cache.go
pkg/pgmodel/cache/series_cache_test.go
pkg/pgmodel/ingestor/dispatcher.go
pkg/pgmodel/ingestor/ingestor.go
pkg/pgmodel/ingestor/ingestor_sql_test.go
pkg/tests/end_to_end_tests/drop_test.go
pkg/tests/end_to_end_tests/ha_single_promscale_test.go

Grow cache mechanism was already implemented. This PR mostly refactors the code to make it more generic so we can re-use

Grow inverted labels cache if needed

---

CHANGELOG.md
docs/mixin/dashboards/promscale.json
pkg/api/metrics.go
pkg/pgmodel/ingestor/trace/writer.go
pkg/pgmodel/metrics/ingest.go

This commit also removes the metric promscale_ingest_items_received_total which is not used anywhere and the same information can be now obtained using the newly introduced `promscale_ingest_items_received_*` histogram metric.
This is how it looks on Promscale dashboard
- ~~[ ] Alerting? - I'm not sure how feasible it would be when considering low ingestion use cases.~~

Add histogram to track number samples/metadata/span sent per request

---

CHANGELOG.md
docs/vacuum.md
pkg/tests/end_to_end_tests/vacuum_test.go
pkg/vacuum/vacuum.go

We have seen instances in which compresses chunks are missing statistics. Autovacuum ignores tables that are missing statistics. Analyzing these tables does not help since we rarely modify chunks after they are compressed. Therefore, these chunks are ignored until they pass the vacuum_freeze_max_age. This can be bad for performance. So, the vacuum engine makes a second pass looking for these chunks and vacuums them. We only use one worker for these.
See also: https://github.com/timescale/promscale_extension/pull/595

Vacuum compressed chunks missing stats

---

pkg/vacuum/vacuum.go
pkg/vacuum/vacuum_test.go

Adjusts vacuum engine metrics to add a `workload` label to keep separate metrics per workload.

Track metrics per workload in vacuum engine

---

pkg/api/alerts.go
pkg/api/metrics.go
pkg/api/query.go
pkg/api/query_exemplar.go
pkg/api/query_range.go
pkg/api/query_range_test.go
pkg/api/query_test.go
pkg/api/read.go
pkg/api/router.go
pkg/api/rules.go
pkg/api/write_test.go
pkg/jaeger/store/store.go
pkg/pgmodel/metrics/query.go

Since query timeout and cancel use the same error code we need an additional metric label to track what happened. This should also help with having better alerting control.

Additional label for query metric 

---

CHANGELOG.md
go.mod
go.sum
pkg/pgmodel/common/schema/schema.go
pkg/pgmodel/ingestor/copier.go
pkg/pgmodel/model/sql_test_utils.go
pkg/pgxconn/copy_from.go
pkg/pgxconn/pgx_conn.go
pkg/tests/testsupport/mock_pgx_conn.go

The CopyFrom command from pgx requires the OIDs of the data types is
going to insert when constructing the binary message that contains
the data.
To retrieve the OIDs a statement is prepared per COPY operation. In our
case the statements are very simmilar:
```
copy {tableName} ( `time`, `value`, `series_id` ) from stdin binary
```
These statements can be cached, the problem is that we will have a cache
entry per table name.
Since we always insert to the same columns and we know the OIDs of the
columns we are going to be inserting to, we can avoid the extra
roundtrip and the cache by manually passing the OIDs.
This custom copy command is basically a copy of the pgx CopyCommand that
accepts the list of OIDs.
Please take into account the following non-code changes that you may need to make …

Custom COPY with only one DB roundtrip
